### ISSUE TITLE
nydusd vs containerd-nydus-grpc and setup on Kubernetes

### ISSUE THREAD

**Issue by will-ds** [dragonflyoss/image-service#103]
My ultimate goal is to be able to run the image service on Kubernetes, but first I'm having trouble understanding where `nydusd` and `containerd-nydus-grpc` fit into the bigger picture.

Where is the `nydusd` daemon used vs the `containerd-nydus-grpc` daemon? If I had a nydus image stored in a registry, and I wanted to use the image service to pull and run this image on kubernetes (lets assume GKE with containerd optimized os on the nodes) which daemon would I use? Lets also assume these images could be scheduled on multiple nodes -- which daemon would be used in the daemonset?

In general, any insight onto how to get this up and running on Kubernetes would be much appreciated.

**Comment by liubogithub** [comment]
>Where is the nydusd daemon used vs the containerd-nydus-grpc daemon?

`containerd-nydus-grpc` is the remote snapshotter which invokes `nydusd` to do the real job for preparing rootfs of the running container.  IOW, `containerd-nydus-grpc` is the only daemon we need to run during setup.

More details are available at [here](https://github.com/dragonflyoss/image-service/blob/7c982b2db3282d2616d37134cef8dd9ec2df426d/docs/containerd-env-setup.md#start-containerd-snapshotter-for-nydus).

Thanks.

**Comment by will-ds** [comment]
Thank you!
