### ISSUE TITLE
nydus-test: randomly failure of functional-test/test_nydus.py::test_signal_handling

### ISSUE THREAD

**Issue by jiangliu** [dragonflyoss/image-service#1037]
We have observed that `functional-test/test_nydus.py::test_signal_handling` of nydus-test fails randomly.
https://github.com/dragonflyoss/image-service/actions/runs/4049471394/jobs/6965874746

**Comment by adamqqqplay** [comment]
@jiangliu Hi, this issue does not seem to have appeared again.
I will close this issue, please reopen if there is a problem.
