### ISSUE TITLE
need a FAQ document

### ISSUE THREAD

**Issue by hsiangkao** [dragonflyoss/image-service#1099]
Really, any mature project should have a formal FAQ.

https://zlib.net/zlib_faq.html
https://prev.rust-lang.org/en-US/faq.html
https://tldp.org/FAQ/Linux-FAQ/
https://www.kernel.org/category/faq.html
https://www.linux-kvm.org/page/FAQ
https://ffmpeg.org/faq.html
https://github.com/containerd/nerdctl/blob/main/docs/faq.md

Since this document has been ignored for months, I have to mark this as an issue to people who care this!

In addition, why such trick is assumed by users to know this in advance without a FAQ??
https://github.com/dragonflyoss/image-service/issues/1097

**Comment by adamqqqplay** [comment]
Fixed in: https://github.com/dragonflyoss/image-service/wiki/FAQ
