### ISSUE TITLE
nydusify convert will download blobs for all platforms

### ISSUE THREAD

**Issue by mofishzz** [dragonflyoss/image-service#1142]
nydusify convert is slow when I convert golang image：
```
nydusify convert  --source golang:latest --target myrepo/golang:latest
```
The size of the image is 297.12 MB , but it takes 8 minutes to pull the image :
```
INFO[2023-03-07T16:38:20+08:00] pulling image docker.io/library/golang:latest  module=converter
INFO[2023-03-07T16:46:38+08:00] pulled image docker.io/library/golang:latest, elapse 8m18.683841192s  module=converter
```
The size of the tmp/blobs/sha256 directory is 6.2G. It seems that nydusify has downloaded blobs for all platforms.

nydusify version:
```
nydusify -v
Nydusify version
Version	: v2.2.0
Revision	: a38f6b8d6257af90d59880265335dd55fab07668
Go version	: go1.18.10
Build time	: 2023-03-01T10:03:11
```

**Comment by imeoer** [comment]
Thanks for the report, this is indeed a bug, will fix it later.

**Comment by imeoer** [comment]
We are working on https://github.com/dragonflyoss/image-service/pull/1146 to fix this.

**Comment by imeoer** [comment]
Hi @mofishzz, it has been fixed in https://github.com/dragonflyoss/image-service/pull/1146, PTAL.
