### ISSUE TITLE
Fail to use nydus-image check -v

### ISSUE THREAD

**Issue by Desiki-high** [dragonflyoss/image-service#1160]
Fail to use nydus-image check -v to get information on bootstrap
![image](https://user-images.githubusercontent.com/59167816/226309795-4efd510d-c7c3-4dd6-999f-e132c9b4cc92.png)
image: alpine:3.17.2
image build cmd: ./nydusify convert --source alpine:3.17.2 --target dockerhub.kubekey.local/dfns/alpine_nydus:3.17.2 --target-insecure --fs-version 5
nydusify build commit:  54723319d5d5a3d412d6e22475ee9c19e0f4824c
nydus-image build commit : 54723319d5d5a3d412d6e22475ee9c19e0f4824c
nydusd build commit: 54723319d5d5a3d412d6e22475ee9c19e0f4824c
config:
{
    "device": {
        "backend": {
            "type": "registry",
            "config": {
                "scheme": "https",
                "host": "dockerhub.kubekey.local",
                "skip_verify": true,
                "auth": ""
            }
        },
        "cache": {
            "type": "blobcache",
            "config": {
                "work_dir": "/var/lib/nydus/cache/"
            }
        }
    },
    "mode": "direct",
    "digest_validate": false,
    "iostats_files": true,
    "enable_xattr": true,
    "access_pattern": true,
    "latest_read_files": true,
    "amplify_io": 0,
    "fs_prefetch": {
        "enable": false,
        "threads_count": 4,
        "merging_size": 131072,
        "bandwidth_rate": 1048576,
        "prefetch_all": false
    }
}

**Comment by Desiki-high** [comment]
when use the nydus-image from https://github.com/dragonflyoss/image-service/releases/tag/v2.2.0 , it works fine

**Comment by imeoer** [comment]
cc @jiangliu It seems related to https://github.com/dragonflyoss/image-service/pull/1156.

**Comment by jiangliu** [comment]
@imeoer Could we add some ci test cases to cover this?

**Comment by imeoer** [comment]
> Could we add some ci test cases to cover this?

We can add one in the smoke test.
