### ISSUE TITLE
Proposal: Compare the current benchmark tests with the master branch's.

### ISSUE THREAD

**Issue by Desiki-high** [dragonflyoss/image-service#1221]
Reference: https://github.com/dragonflyoss/image-service/pull/1219#issuecomment-1510614518.

We need to compare the benchmark tests between the PR and the master branch's.

**Comment by adamqqqplay** [comment]
@Desiki-high Hi, Thanks for your work, the benchmarks are now working. 

I have a small suggestion, can you let github-actions bot modify the previous comments instead of re-comments after each test. In this way, the comment page of the PR can be made clearer.
