### ISSUE TITLE
Reuse the rust caches

### ISSUE THREAD

**Issue by Desiki-high** [dragonflyoss/image-service#1260]
### And the caches is approaching total cache storage [limit](https://github.com/dragonflyoss/image-service/actions/caches). We have too many rust caches:
![image](https://user-images.githubusercontent.com/59167816/236424608-6074e88a-b95a-4226-8350-bfb3e763854a.png)
![image](https://user-images.githubusercontent.com/59167816/236423996-c1e8793b-7d03-41e7-b464-854b116c885b.png)
![image](https://user-images.githubusercontent.com/59167816/236424040-618afe60-96f9-4d2e-b99d-89c5005b349b.png)
![image](https://user-images.githubusercontent.com/59167816/236424534-735fadad-ad44-4d04-9c92-c3d8d2050afb.png)

## So maybe we can reuse these caches by ```shared-key``` like https://github.com/Swatinem/rust-cache/issues/127?
1. https://github.com/dragonflyoss/image-service/blob/7a48992bce92aad5116907734e388719c3dafe5b/.github/workflows/benchmark.yml#L48
2. https://github.com/dragonflyoss/image-service/blob/7a48992bce92aad5116907734e388719c3dafe5b/.github/workflows/convert.yml#L51
3. https://github.com/dragonflyoss/image-service/blob/7a48992bce92aad5116907734e388719c3dafe5b/.github/workflows/smoke.yml#L88
4. https://github.com/dragonflyoss/image-service/blob/7a48992bce92aad5116907734e388719c3dafe5b/.github/workflows/smoke.yml#L112
5. https://github.com/dragonflyoss/image-service/blob/7a48992bce92aad5116907734e388719c3dafe5b/.github/workflows/smoke.yml#L603
6. https://github.com/dragonflyoss/image-service/blob/7a48992bce92aad5116907734e388719c3dafe5b/.github/workflows/smoke.yml#L619

**Comment by adamqqqplay** [comment]
We might be able to use the same version rust-cache. For example, uniformly adjusted to `Swatinem/rust-cache@v2` in the yaml file.

**Comment by Desiki-high** [comment]
```nydus-build``` and ```nydus-build-master``` can easily reuse the same cache because of the same dependences. But ```nydus-unit-test``` and ```nydus-unit-test-coverage``` maybe have different dependences, so if we use the rust cache uploaded by ```nydus-unit-test``` can not accelerate the nydus build?

Maybe we can only reuse the rust caches between ```nydus-build``` and ```nydus-build-master``` in smoke and benchmark?

**Comment by imeoer** [comment]
> Maybe we can only reuse the rust caches between `nydus-build` and `nydus-build-master` in smoke and benchmark?

Should be ok.
