### ISSUE TITLE
Proposal: support logger output in unit test

### ISSUE THREAD

**Issue by hangvane** [dragonflyoss/image-service#1290]
Seems that there's no easy way to show the logger output in unit test for debugging currently, even with the command arg `--nocapture`:
```shell
cargo test --package nydus-storage --lib -- meta::tests::test_load_meta_ci_zran_get_chunks_compressed --exact --nocapture
```

`flexi-logger` has supported output in unit test since [0.25.3](https://github.com/emabee/flexi_logger/blob/master/CHANGELOG.md#0253---2023-03-04), so we can initialize `flexi_logger` in test:
```rust

#[test]
    fn example_test() {
        use flexi_logger::*;
        Logger::try_with_env_or_str("trace")
            .map_err(|_e| enosys!())
            .unwrap()
            .format(colored_opt_format)
            .write_mode(WriteMode::SupportCapture)
            .start()
            .map_err(|e| eother!(e))
            .unwrap();
        debug!("some debug outputs");
```

Maybe a more elegant way is to reuse [`src/logger.rs#setup_logging()`](https://github.com/dragonflyoss/image-service/blob/d75167992339be64880fff27bfe09a94a9f96396/src/logger.rs#L95). But the `logger.rs` is placed in root package `nydus-rs` that cannot call from child packages such as `nydus-storage`. Move `logger.rs` to `nydus-utils` seems to be a good way.

**Comment by adamqqqplay** [comment]
Maybe you could try `make ut-nextest`, it uses cargo nextest which may provide better output than cargo test.

**Comment by hangvane** [comment]
> Maybe you could try `make ut-nextest`, it uses cargo nextest which may provide better output than cargo test.

It works. Thanks!
