### ISSUE TITLE
add doc for runtime-level snapshotter usage

### ISSUE THREAD

**Issue by imeoer** [dragonflyoss/image-service#1296]
https://github.com/containerd/containerd/pull/6899 (released in containerd >=1.7.0)

We should allow users to choose the snapshotter when running pods, otherwise when upgrading the nydus snapshotter (deployed by daemonset, especially in helm charts), users need to change the global snapshotter configuration of containerd to the overlay, which will affect the experience.

cc @adamqqqplay @zyfjeff

**Comment by adamqqqplay** [comment]
Thanks for the information, I will take a look later.
