### ISSUE TITLE
nydusify mount subcommand shouldn't require backend option

### ISSUE THREAD

**Issue by imeoer** [dragonflyoss/image-service#1306]
```
$ nydusify mount --target localhost:5000/nginx:latest-nydus
...
FATA[2023-05-31T02:20:35Z] Required flag "backend-type" not set
```

When the blobs of target image are all stored in the registry, the `nydusify mount` subcommand shouldn't require `--backend-type` and `--backend-config` options, just like the `nydusify check` subcommand.

**Comment by lyj199907** [comment]
@imeoer I will try to fix it later
