### ISSUE TITLE
Compatibility of cache is required.

### ISSUE THREAD

**Issue by ccx1024cc** [dragonflyoss/image-service#1320]
## Cache of 2.2 is not compatible to 1.6.6
It's easy to delete cache files for recovery, but hard to know at first time. 

### Version of nydus being used (nydusd --version)

Version:        v2.2.1-20-g160ad41bf
Git Commit:     160ad41bf20821837cd5aa6835991eaec9ba4199
Build Time:     2023-06-14T06:53:18.980065099Z
Profile:        release
Rustc:          rustc 1.66.1 (90743e729 2023-01-10)

Version:        1.6.2
Git Commit:     57447839327f197da792c5ae0bc0e31b503aca86
Build Time:     Tue, 18 Apr 2023 10:22:54 +0000
Profile:        release
Rustc:          rustc 1.52.1 (9bc8c42bb 2021-05-09)

### client command line used
```
sudo ./bin/nydusd-1.6 --config config/config.json --mountpoint mnt --bootstrap rafs/image.boot --log-level info
cat ${sth.}
kill ${nydusd-1.6}
sudo ./bin/nydusd-2.2 --config config/config.json --mountpoint mnt --bootstrap rafs/image.boot --log-level info
cat ${same thing}

The result is out of control.
```

### config file (does not matter)
```
{
    "device": {
        "backend": {
            "type": "localfs",
            "config": {
                "blob_file": "/tmp/nydus/rafs/image.blob"
            }
        },
        "cache": {
            "type": "blobcache",
            "config": {
                "work_dir": "/tmp/nydus/cache"
            }
        }
    },
    "mode": "direct",
    "digest_validate": false,
    "enable_xattr": true,
    "latest_read_files": true,
    "fs_prefetch": {
        "enable": false,
        "threads_count": 10,
        "merging_size": 131072,
        "bandwidth_rate": 10485760
    }
}
```

### rafs fs build(does not matter)
sudo ./bin/nydus-image-1.6 create --bootstrap rafs/image.boot --blob rafs/image.blob build

**Comment by imeoer** [comment]
It should have been fixed in https://github.com/dragonflyoss/image-service/pull/1417.
