### ISSUE TITLE
Failed to start singleton daemon: Invalid argument (os error 22)

### ISSUE THREAD

**Issue by mingfukuang** [dragonflyoss/image-service#1342]
## Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._

### Version of nydus being used (nydusd --version)
Version:        v2.2.1
Git Commit:     04fb92c5aa980deedf62e69cc2294195a88bab31
Build Time:     2023-05-04T07:28:49.522159639Z
Profile:        release
Rustc:          rustc 1.66.1 (90743e729 2023-01-10)

### Version of nydus-snapshotter being used (containerd-nydus-grpc --version)
Version:     v0.9.0
Revision:    2c811d7b2e57a556791c3bedfbaf1db95267131d
Go version:  go1.20.3
Build time:  2023-06-17T11:10:15

### Kernel information (uname -r)
4.19.91-26.an8.x86_64

### containerd-nydus-grpc command line used, if applicable (ps aux | grep containerd-nydus-grpc)
```
containerd-nydus-grpc  --nydusd-config /etc/nydus/nydusd-config.fscache.json    --fs-driver fscache  --log-level debug  --log-to-stdout
```
# cat  /etc/nydus/nydusd-config.fscache.json
{
  "type": "bootstrap",
  "config": {
    "backend_type": "registry",
    "backend_config": {
      "scheme": "http"
    },
    "cache_type": "fscache"
  }
}

#  containerd-nydus-grpc  --nydusd-config /etc/nydus/nydusd-config.fscache.json    --fs-driver fscache  --log-level debug  --log-to-stdout
INFO[0000] fscache driver only supports 'shared' mode, override daemon mode from 'dedicated' to 'shared'
INFO[2023-07-04T03:46:34.421179021+08:00] Start nydus-snapshotter. Version: v0.9.0, PID: 2386593, FsDriver: fscache, DaemonMode: multiple
INFO[2023-07-04T03:46:34.421687757+08:00] Trying to update bucket records from v1.0 to v1.1 ...
INFO[2023-07-04T03:46:34.421981819+08:00] Run daemons monitor...
INFO[2023-07-04T03:46:34.422073261+08:00] initializing the shared nydus daemon
INFO[2023-07-04T03:46:34.422504666+08:00] nydusd command: /usr/local/bin/nydusd singleton --fscache /var/lib/containerd-nydus/cache --apisock /var/lib/containerd-nydus/socket/cihib6htfriqibe96kb0/api.sock --log-level debug
INFO[2023-07-04T03:46:34.422938725+08:00] for fscache mode enable syncRemove
[2023-07-04 03:46:34.423858 +08:00] INFO Program Version: v2.2.1, Git Commit: "04fb92c5aa980deedf62e69cc2294195a88bab31", Build Time: "2023-05-04T07:28:49.522159639Z", Profile: "release", Rustc Version: "rustc 1.66.1 (90743e729 2023-01-10)"
[2023-07-04 03:46:34.423901 +08:00] INFO Set rlimit-nofile to 1000000, maximum 1000000
[2023-07-04 03:46:34.423914 +08:00] INFO Start Nydus daemon in singleton mode!
[2023-07-04 03:46:34.423975 +08:00] INFO Create fscache instance at /var/lib/containerd-nydus/cache with tag <none>, 4 working threads
[2023-07-04 03:46:34.423988 +08:00] INFO fscache: create FsCacheHandler with dir /var/lib/containerd-nydus/cache, tag <None>
[2023-07-04 03:46:34.424029 +08:00] **ERROR [src/bin/nydusd/main.rs:582] Failed to start singleton daemon: Invalid argument (os error 22)**
**Error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }**
ERRO[2023-07-04T03:46:34.530651614+08:00] Process 2386609 has been a zombie
ERRO[2023-07-04T03:46:34.530734822+08:00] Nydusd cihib6htfriqibe96kb0 probably not started

**Comment by imeoer** [comment]
Where are the docs you finding? The fscache support from `4.19.91-27 / 5.10.134-12`.

**Comment by mingfukuang** [comment]
> Where are the docs you finding? The fscache support from `4.19.91-27 / 5.10.134-12`.

https://github.com/dragonflyoss/image-service/blob/662117a0656811a854901d7d94ee7ec6e5180439/docs/nydus-fscache.md

**Comment by imeoer** [comment]
> https://github.com/dragonflyoss/image-service/blob/662117a0656811a854901d7d94ee7ec6e5180439/docs/nydus-fscache.md

@adamqqqplay Maybe we can document the OpenAnolis kernel version in this doc?

**Comment by adamqqqplay** [comment]
> > https://github.com/dragonflyoss/image-service/blob/662117a0656811a854901d7d94ee7ec6e5180439/docs/nydus-fscache.md
> 
> @adamqqqplay Maybe we can document the OpenAnolis kernel version in this doc?

OK, I will update it soon.
