### ISSUE TITLE
After containerd-nydus-grpc is restarted, the recovery process is slow

### ISSUE THREAD

**Issue by xiangshen123** [dragonflyoss/image-service#1362]
After my k8snode was restarted, I restarted containerd-nydus-grpc. The image pulling error occurred on the restarted machine, as shown in the following figure. However, after about 5 minutes, the node reported an error and the image could be pulled normally
![image](https://github.com/dragonflyoss/image-service/assets/124766156/e4a5cf59-807f-446d-a95a-41fbad2488df)

**Comment by changweige** [comment]
The improvement has been merged into `nydus-snaphsotter` and will be released soon. So closing this 😁
