### ISSUE TITLE
relationship with DADI?

### ISSUE THREAD

**Issue by luodw** [dragonflyoss/image-service#14]
What is the relationship between Nydus with this Issue https://github.com/containerd/containerd/issues/2267?

**Comment by bergwolf** [comment]
They are unrelated.

**Comment by luodw** [comment]
> They are unrelated.
How to upgrade Nydus daemon service？As I know, when fuse daemon restart, the fuse connection will disconnect and the container process will read/write failed. how Nydus gracefully solved this situation?

**Comment by bergwolf** [comment]
@luodw Upgrading is something we might look at in the future. Right now we are more focused on the whole architecture and the image format.

**Comment by xujihui1985** [comment]
@luodw we have solved this situation inside Alipay, nydus has deployed in several clusters with live migrating enabled, we will also bring that to public in right time, please keep eye on this repo

**Comment by luodw** [comment]
> @luodw we have solved this situation inside Alipay, nydus has deployed in several clusters with live migrating enabled, we will also bring that to public in right time, please keep eye on this repo

@xujihui1985 ok, I am interested in image  lazy load and I will keep eye on Nydus. One more question, What is the difference between Nydus and DADI？

**Comment by xujihui1985** [comment]
@luodw DADI is a also a great technology in terms of image lazy load, the difference is DADI is focus on block level accelerate while nydus is filesystem level, we care more about the ability of "content aware" that filesystem can provide us like file access pattern, meta data, security, etc. and these ability give us more imagination in the future.

**Comment by luodw** [comment]
> @luodw DADI is a also a great technology in terms of image lazy load, the difference is DADI is focus on block level accelerate while nydus is filesystem level, we care more about the ability of "content aware" that filesystem can provide us like file access pattern, meta data, security, etc. and these ability give us more imagination in the future.

@xujihui1985 Nydus is similar to https://github.com/containerd/stargz-snapshotter，But Stargz Snapshotter still does not solve daemon restart gracefully. I think if Nydus support gracefully restart，It will be more used.

**Comment by luodw** [comment]
> > @luodw DADI is a also a great technology in terms of image lazy load, the difference is DADI is focus on block level accelerate while nydus is filesystem level, we care more about the ability of "content aware" that filesystem can provide us like file access pattern, meta data, security, etc. and these ability give us more imagination in the future.
> 
> @xujihui1985 Nydus is similar to [https://github.com/containerd/stargz-snapshotter，But](https://github.com/containerd/stargz-snapshotter%EF%BC%8CBut) Stargz Snapshotter still does not solve daemon restart gracefully. I think if Nydus support gracefully restart，It will be more used.

Another question, how to integrate with p2p？ Every file go through p2p distrubution?

**Comment by jiangliu** [comment]
> > @luodw we have solved this situation inside Alipay, nydus has deployed in several clusters with live migrating enabled, we will also bring that to public in right time, please keep eye on this repo
> 
> @xujihui1985 ok, I am interested in image lazy load and I will keep eye on Nydus. One more question, What is the difference between Nydus and DADI？

You may think DADI as "ext4 + device mapper + p2p",  and actually deployment seems like ext4fs + nbd + user space device mapper + p2p.

nydus has combined "ext4 + device mapper" into rafs, a file system for container image.

**Comment by liubogithub** [comment]
> > > @luodw DADI is a also a great technology in terms of image lazy load, the difference is DADI is focus on block level accelerate while nydus is filesystem level, we care more about the ability of "content aware" that filesystem can provide us like file access pattern, meta data, security, etc. and these ability give us more imagination in the future.
> > 
> > 
> > @xujihui1985 Nydus is similar to [https://github.com/containerd/stargz-snapshotter，But](https://github.com/containerd/stargz-snapshotter%EF%BC%8CBut) Stargz Snapshotter still does not solve daemon restart gracefully. I think if Nydus support gracefully restart，It will be more used.
> 
> Another question, how to integrate with p2p？ Every file go through p2p distrubution?

p2p serves as a proxy between registry and dragonfly image service on node.
Yes, file are split into chunks which are fetched from the registry through p2p when it's available.

**Comment by changweige** [comment]
> > @luodw DADI is a also a great technology in terms of image lazy load, the difference is DADI is focus on block level accelerate while nydus is filesystem level, we care more about the ability of "content aware" that filesystem can provide us like file access pattern, meta data, security, etc. and these ability give us more imagination in the future.
> 
> @xujihui1985 Nydus is similar to [https://github.com/containerd/stargz-snapshotter，But](https://github.com/containerd/stargz-snapshotter%EF%BC%8CBut) Stargz Snapshotter still does not solve daemon restart gracefully. I think if Nydus support gracefully restart，It will be more used.

Yes. With live-upgrade and failover, it will be more suitable for a productive deployment. But it will be quite coupled with how you deploy Nydus. We are suspicious of the ubiquity.

**Comment by luodw** [comment]
> > > > @luodw DADI is a also a great technology in terms of image lazy load, the difference is DADI is focus on block level accelerate while nydus is filesystem level, we care more about the ability of "content aware" that filesystem can provide us like file access pattern, meta data, security, etc. and these ability give us more imagination in the future.
> > > 
> > > 
> > > @xujihui1985 Nydus is similar to [https://github.com/containerd/stargz-snapshotter，But](https://github.com/containerd/stargz-snapshotter%EF%BC%8CBut) Stargz Snapshotter still does not solve daemon restart gracefully. I think if Nydus support gracefully restart，It will be more used.
> > 
> > 
> > Another question, how to integrate with p2p？ Every file go through p2p distrubution?
> 
> p2p serves as a proxy between registry and dragonfly image service on node.
> Yes, file are split into chunks which are fetched from the registry through p2p when it's available.

I am curious about the reasonability that every little file(eg. /etc/hosts) go through p2p distribution,  torrent meta file may be bigger then distributed file and it will produce many torrent meta file due to the files in /etc, /usr and so on.  So, is it a good idea to group files into a chunk(size may be 32MB, 64MB..)，it will be friendly to p2p and can also use the principle of locality.  Recently, we also have been considering image acceleration.

**Comment by jiangliu** [comment]
> > > > > @luodw DADI is a also a great technology in terms of image lazy load, the difference is DADI is focus on block level accelerate while nydus is filesystem level, we care more about the ability of "content aware" that filesystem can provide us like file access pattern, meta data, security, etc. and these ability give us more imagination in the future.
> > > > 
> > > > 
> > > > @xujihui1985 Nydus is similar to [https://github.com/containerd/stargz-snapshotter，But](https://github.com/containerd/stargz-snapshotter%EF%BC%8CBut) Stargz Snapshotter still does not solve daemon restart gracefully. I think if Nydus support gracefully restart，It will be more used.
> > > 
> > > 
> > > Another question, how to integrate with p2p？ Every file go through p2p distrubution?
> > 
> > 
> > p2p serves as a proxy between registry and dragonfly image service on node.
> > Yes, file are split into chunks which are fetched from the registry through p2p when it's available.
> 
> I am curious about the reasonability that every little file(eg. /etc/hosts) go through p2p distribution, torrent meta file may be bigger then distributed file and it will produce many torrent meta file due to the files in /etc, /usr and so on. So, is it a good idea to group files into a chunk(size may be 32MB, 64MB..)，it will be friendly to p2p and can also use the principle of locality. Recently, we also have been considering image acceleration.

That's exactly the way we do p2p. Nydus/rafs combines all small/big data files into a blob file in chunks. The only blob file will be handled by the P2P network.

**Comment by luodw** [comment]
I test nydus, I have a question, how to integrate nydus with containerd?  I see nydusd will prepare a fuse mountpoint, but how to give this to containerd as a rootfs? Maybe it need containerd snapshotter as Stargz Snapshotter?

**Comment by changweige** [comment]
> I test nydus, I have a question, how to integrate nydus with containerd? I see nydusd will prepare a fuse mountpoint, but how to give this to containerd as a rootfs? Maybe it need containerd snapshotter like Stargz Snapshotter?

Yes. Your guess is right. We are still preparing the needed snapshotter open-source stuff and will push it to this repo as soon as it is ready. Perhaps, @xujihui1985 can give some details about this.

**Comment by luodw** [comment]
> > I test nydus, I have a question, how to integrate nydus with containerd? I see nydusd will prepare a fuse mountpoint, but how to give this to containerd as a rootfs? Maybe it need containerd snapshotter like Stargz Snapshotter?
> 
> Yes. Your guess is right. We are still preparing the needed snapshotter open-source stuff and will push it to this repo as soon as it is ready. Perhaps, @xujihui1985 can give some details about this.

so, I wonder how to use nydus in production environment？

**Comment by xujihui1985** [comment]
> > > I test nydus, I have a question, how to integrate nydus with containerd? I see nydusd will prepare a fuse mountpoint, but how to give this to containerd as a rootfs? Maybe it need containerd snapshotter like Stargz Snapshotter?
> > 
> > 
> > Yes. Your guess is right. We are still preparing the needed snapshotter open-source stuff and will push it to this repo as soon as it is ready. Perhaps, @xujihui1985 can give some details about this.
> 
> so, I wonder how to use nydus in production environment？

nydus-snapshotter will be open-sourced soon, it is under review at this moment

**Comment by luodw** [comment]
Is there a plan to push buildkit support nydus format image build? I see buildkit has been in supporting stargz image build.

**Comment by jiangliu** [comment]
Yes, there's plan for upstreaming the buildkit related work.

**Comment by xujihui1985** [comment]
@luodw https://github.com/moby/buildkit/issues/1663 do you mean this issue? I thought buildkit would use stargz to accelerate base image pulling which is a great feature, but at this moment it didn't mention anything about build stargz image natively. Anyway buildkit support is undergoing

**Comment by luodw** [comment]
@xujihui1985 yeah, now, stargz and nydus should pull image and then convert when building image, it will take a long time.  If we can build nydus image without OCI image, it will have a good experience.

**Comment by xujihui1985** [comment]
@luodw absolutely, build nydus/stargz image natively will tremendously reduce the cost of image converting

**Comment by luodw** [comment]
@xujihui1985 thank you for your reply.  recently, I test nydus with kata,  I encounter  a probrem.  kata has virtiofsd and nydus has fusefs, so application in guest VM will go through two fuse layer when reading files. so  I wonder what is the best practice to use Nydus with kata?

**Comment by liubogithub** [comment]
@luodw Nydusd supports both fusedev and virtiofs interface (via `nydusd --sock` )
https://github.com/dragonflyoss/image-service/blob/7c982b2db3282d2616d37134cef8dd9ec2df426d/src/bin/nydusd/main.rs#L129

**Comment by luodw** [comment]
@liubogithub I check out the  example, nydus only support a read only image layer.  so if we want to use nydusd instead of virtiofsd, It should supply writable container layer or by other ways?

**Comment by jiangliu** [comment]
yes, the recommend way is to use overlayfs in guest to bind nydus and another rw layer, the rw layer may be hosted by another virtio-blk device.

**Comment by liubogithub** [comment]
@luodw Should you have further questions, please reopen the issue or open a new one, thanks.
