### ISSUE TITLE
Use PR check tools to standardize the PR process

### ISSUE THREAD

**Issue by An-DJ** [dragonflyoss/image-service#1431]
## Details about issue

Found that the content in PR is checked by human. 

Such an approach may make mistakes, like the chinese colon in that PR title: #1430

There are many useful tools to help us, such as https://github.com/marketplace/actions/semantic-pull-request

**Comment by imeoer** [comment]
Thanks for the suggestion, we don't restrict the style of PR titles, etc., otherwise this would be unfriendly to new contributors. :)
