### ISSUE TITLE
Pass correct log level from snapshotter to nydusd

### ISSUE THREAD

**Issue by Bowser1704** [dragonflyoss/image-service#145]
https://github.com/dragonflyoss/image-service/blob/b70093212547c1c23d14ee8a0777564d166d02c9/contrib/nydus-snapshotter/pkg/process/manager.go#L129-L135

It seems always set nydusd log level  to be `info`.

**Comment by Bowser1704** [comment]
There seems no graceful way to pass the value to the `Manager` directly, maybe add a field in config is a better way.

**Comment by imeoer** [comment]
@Bowser1704 Thanks for finding this issue, you can propose a PR if you're happy. ;)
