### ISSUE TITLE
Push bootstrap layer: unexpected response: 401 Unauthorized 

### ISSUE THREAD

**Issue by 844700118** [dragonflyoss/image-service#149]
ctr images pull  --plain-http 192.168.1.130:8099/test/nginx:alpine
ctr images push --plain-http  192.168.1.130:8099/test/nginx:alpine
it is successful..

but
nydusify convert --nydus-image /usr/bin/nydus-image --source nginx:alpine --target 192.168.1.130:8099/test/nginx-nydus --target-insecure
The convert failed, what is the reason? Is there any configuration missing? Eagerly looking forward to reply.

vi /etc/containerd/config.toml
[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    [plugins."io.containerd.grpc.v1.cri".registry]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
          endpoint = ["https://registry.cn-hangzhou.aliyuncs.com"]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."192.168.1.130:8099"]
          endpoint = ["http://192.168.1.130:8099"]
      [plugins."io.containerd.grpc.v1.cri".registry.configs]
        [plugins."io.containerd.grpc.v1.cri".registry.configs."192.168.1.130:8099"]
          [plugins."io.containerd.grpc.v1.cri".registry.configs."192.168.1.130:8099".tls]
            insecure_skip_verify = true
          [plugins."io.containerd.grpc.v1.cri".registry.configs."192.168.1.130:8099".auth]
            username = "admin"
            password = "Harbor12345"

/etc/nydusd-config.json
{
	"device": {
		"backend": {
			"type": "registry",
			"config": {
				"scheme": "http",
				"host": "192.168.1.130:8099",
				"auth": "YWRtaW46SGFyYm9yMTIzNDU=",
				"timeout": 5,
				"connect_timeout": 5,
				"retry_limit": 0
			}
		},
		"cache": {
			"type": "blobcache",
			"compressed": true,
			"config": {
				"work_dir": "cache"
			}
		}
	},
	"mode": "direct",
	"digest_validate": false,
	"iostats_files": true,
	"enable_xattr": false,
	"fs_prefetch": {
		"enable": true,
		"threads_count": 10,
		"bandwidth_rate": 1048576
	}
}

runc -v
    runc version 1.0.0
    commit: v1.0.0-0-g84113eef
    spec: 1.0.2-dev
    go: go1.15.14
    libseccomp: 2.3.1

containerd -v
     containerd github.com/containerd/containerd v1.4.8 7eba5930496d9bbe375fdf71603e610ad737d2b2

**Comment by changweige** [comment]
Generally, `nydusify` uses authentacation information from docker, which might be located at `~/.docker` .
So please try to use docker pull/push to verify your configuration correction.

**Comment by 844700118** [comment]
> Generally, `nydusify` uses authentacation information from docker, which might be located at `~/.docker` .
> So please try to use docker pull/push to verify your configuration correction.

It succeeded, thank you very much for your help.
