### ISSUE TITLE
expected cgroupsPath to be of format "slice:prefix:name" for systemd cgroups

### ISSUE THREAD

**Issue by 844700118** [dragonflyoss/image-service#150]
**1. the question: crictl runp container-config.yaml pod-config.yaml error**
**FATA[0000] run pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: OCI runtime create failed: expected cgroupsPath to be of format "slice:prefix:name" for systemd cgroups, got "/k8s.io/769b91ee7615e3fcab82235c0ab0c5bf23cddbc7cc9ce22e1d82d7076e62118c" instead: unknown**

**2. configuration information**
**vi /etc/containerd/config.toml**
version = 2
root = "/var/lib/containerd"
state = "/run/containerd"
[proxy_plugins]
  [proxy_plugins.nydus]
    type = "snapshot"
    address = "/run/containerd/containerd-nydus-grpc.sock"
......
[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
	sandbox_image = "registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2"
	systemd_cgroup = true
	[plugins."io.containerd.grpc.v1.cri".containerd]
	  snapshotter = "nydus"
	  disable_snapshot_annotations = false
	  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
		[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
		  runtime_type = "io.containerd.runtime.v1.linux"
		  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
			SystemdCgroup = true
......

**vi /etc/nydusd-config.json**
{
    "device": {
        "backend": {
            "type": "registry",
            "config": {
                "scheme": "http",
                "host": "192.168.1.130:8099",
                "auth": "YWRtaW46SGFyYm9yMTIzNDU=",
                "timeout": 5,
                "connect_timeout": 5,
                "retry_limit": 0
            }
        },
        "cache": {
            "type": "blobcache",
            "compressed": true,
            "config": {
                "work_dir": "cache"
            }
        }
    },
    "mode": "direct",
    "digest_validate": false,
    "iostats_files": true,
    "enable_xattr": false,
    "fs_prefetch": {
        "enable": true,
        "threads_count": 10,
        "bandwidth_rate": 1048576
    }
}

**3. configuration information**
runc -v
runc version 1.0.0
commit: v1.0.0-0-g84113eef
spec: 1.0.2-dev
go: go1.15.14
libseccomp: 2.3.1

containerd -v
containerd github.com/containerd/containerd v1.4.8 7eba5930496d9bbe375fdf71603e610ad737d2b2

**4. service status**
**systemctl status containerd -l**
● containerd.service - containerd container runtime
   Loaded: loaded (/etc/systemd/system/containerd.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2021-08-21 11:32:34 CST; 2min 20s ago
     Docs: https://containerd.io
  Process: 182847 ExecStartPre=/sbin/modprobe overlay (code=exited, status=1/FAILURE)
 Main PID: 182851 (containerd)
    Tasks: 14
   Memory: 23.2M
   CGroup: /system.slice/containerd.service
           └─182851 /usr/local/bin/containerd

Aug 21 11:32:34 k8s-master containerd[182851]: time="2021-08-21T11:32:34.348941427+08:00" level=warning msg="The image sha256:7ce0143dee376bfd2937b499a46fb110bda3c629c195b84b1cf6e19be1a9e23b is not unpacked."
Aug 21 11:32:34 k8s-master containerd[182851]: time="2021-08-21T11:32:34.351974462+08:00" level=info msg="Start event monitor"
Aug 21 11:32:34 k8s-master containerd[182851]: time="2021-08-21T11:32:34.351999856+08:00" level=info msg="Start snapshots syncer"
Aug 21 11:32:34 k8s-master containerd[182851]: time="2021-08-21T11:32:34.352008398+08:00" level=info msg="Start cni network conf syncer"
Aug 21 11:32:34 k8s-master containerd[182851]: time="2021-08-21T11:32:34.352012637+08:00" level=info msg="Start streaming server"
Aug 21 11:33:07 k8s-master containerd[182851]: time="2021-08-21T11:33:07.719723332+08:00" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nydus-container,Uid:,Namespace:,Attempt:0,}"
Aug 21 11:33:07 k8s-master containerd[182851]: time="2021-08-21T11:33:07.819571912+08:00" level=warning msg="runtime v1 is deprecated since containerd v1.4, consider using runtime v2"
Aug 21 11:33:07 k8s-master containerd[182851]: time="2021-08-21T11:33:07.821175602+08:00" level=info msg="shim containerd-shim started" address="unix:///run/containerd/s/2912f456fe3662db1686fa2e03cfca1cbf5eea59be26242d73ebcbb4e677f91e" debug=false pid=184112
Aug 21 11:33:07 k8s-master containerd[182851]: time="2021-08-21T11:33:07.846993728+08:00" level=info msg="shim reaped" id=898a5ff42e28f8b140d3b39f95d36529eafd7775a4ced1b74c077217364dfd8e
Aug 21 11:33:07 k8s-master containerd[182851]: time="2021-08-21T11:33:07.961343539+08:00" level=error **msg="RunPodSandbox for &PodSandboxMetadata{Name:nydus-container,Uid:,Namespace:,Attempt:0,} failed, error" error="failed to create containerd task: OCI runtime create failed: expected cgroupsPath to be of format \"slice:prefix:name\" for systemd cgroups, got \"/k8s.io/898a5ff42e28f8b140d3b39f95d36529eafd7775a4ced1b74c077217364dfd8e\" instead: unknown"**

**5. snapshotter containerd-nydus-grpc**
**containerd-nydus-grpc --nydusd-path /usr/bin/nydusd --config-path /etc/nydusd-config.json --log-level trace --root /var/lib/containerd/io.containerd.snapshotter.v1.nydus --address /run/containerd/containerd-nydus-grpc.sock**

{"level":"info","msg":"found 0 daemons running","time":"2021-08-21T11:32:48.792370509+08:00"}
{"key":"k8s.io/24/898a5ff42e28f8b140d3b39f95d36529eafd7775a4ced1b74c077217364dfd8e","level":"info","msg":"prepare key k8s.io/24/898a5ff42e28f8b140d3b39f95d36529eafd7775a4ced1b74c077217364dfd8e parent k8s.io/2/sha256:ba0dae6243cc9fa2890df40a625721fdbea5c94ca6da897acdd814d710149770 labels","parent":"k8s.io/2/sha256:ba0dae6243cc9fa2890df40a625721fdbea5c94ca6da897acdd814d710149770","time":"2021-08-21T11:33:07.808490522+08:00"}
{"key":"k8s.io/24/898a5ff42e28f8b140d3b39f95d36529eafd7775a4ced1b74c077217364dfd8e","level":"info","msg":"prepare for container layer k8s.io/24/898a5ff42e28f8b140d3b39f95d36529eafd7775a4ced1b74c077217364dfd8e","parent":"k8s.io/2/sha256:ba0dae6243cc9fa2890df40a625721fdbea5c94ca6da897acdd814d710149770","time":"2021-08-21T11:33:07.808615638+08:00"}
{"level":"info","msg":"id 18 is data layer, continue to check parent layer","time":"2021-08-21T11:33:07.808633407+08:00"}
{"level":"info","msg":"id 1 is data layer, continue to check parent layer","time":"2021-08-21T11:33:07.808643524+08:00"}
{"level":"info","msg":"id 18 is data layer, continue to check parent layer","time":"2021-08-21T11:33:07.808667378+08:00"}
{"level":"info","msg":"id 1 is data layer, continue to check parent layer","time":"2021-08-21T11:33:07.808734520+08:00"}
{"level":"info","msg":"mount options [workdir=/var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/18/work upperdir=/var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/18/fs lowerdir=/var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/1/fs]","time":"2021-08-21T11:33:07.808782298+08:00"}
{"level":"info","msg":"id 18 is data layer, continue to check parent layer","time":"2021-08-21T11:33:07.818018486+08:00"}
{"level":"info","msg":"id 1 is data layer, continue to check parent layer","time":"2021-08-21T11:33:07.818120232+08:00"}
{"level":"info","msg":"id 18 is data layer, continue to check parent layer","time":"2021-08-21T11:33:07.818148765+08:00"}
{"level":"info","msg":"id 1 is data layer, continue to check parent layer","time":"2021-08-21T11:33:07.818156486+08:00"}
{"level":"info","msg":"mount options [workdir=/var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/18/work upperdir=/var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/18/fs lowerdir=/var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/1/fs]","time":"2021-08-21T11:33:07.818193849+08:00"}
{"level":"info","msg":"cleanup: dirs=[/var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/18]","time":"2021-08-21T11:33:07.979308434+08:00"}
{"dir":"/var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/18","level":"info","msg":"cleanupSnapshotDirectory /var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/18","time":"2021-08-21T11:33:07.982032025+08:00"}
**{"dir":"/var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/18","error":"failed to get daemon by snapshotID (18)","level":"error","msg":"failed to unmount","time":"2021-08-21T11:33:07.983769369+08:00"}**
{"level":"info","msg":"umount nydus daemon of id 18, mountpoint /var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/18","time":"2021-08-21T11:33:07.983817167+08:00"}
{"dir":"/var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/18","error":"failed to get daemon by snapshotID (18)","level":"error","msg":"failed to unmount","time":"2021-08-21T11:33:07.983844400+08:00"}

**Comment by bergwolf** [comment]
looks like a misconfiguration in your runtime setup. Can you start a normal container without nydus?

**Comment by 844700118** [comment]
> looks like a misconfiguration in your runtime setup. Can you start a normal container without nydus?

Can run the container normally.
ctr run -d 192.168.1.130:8099/test/nginx:alpine nginx-alpine
[root@master /opt/nydusd]#nerdctl ps
CONTAINER ID    IMAGE                                   COMMAND                   CREATED           STATUS    PORTS    NAMES
nginx-alpine    192.168.1.130:8099/test/nginx:alpine    "/docker-entrypoint.…"    13 seconds ago    Up

**Comment by 844700118** [comment]
Delete the directory /var/lib/containerd/io.containerd.snapshotter.v1.nydus, restart 2 services containerd-nydus-grpc containerd, report another error :  failed to create snapshot: missing parent bucket: not found https://github.com/dragonflyoss/image-service/issues/151

**Comment by liubogithub** [comment]
No response after Aug 31 2021.
