### ISSUE TITLE
nydusd No such device

### ISSUE THREAD

**Issue by 844700118** [dragonflyoss/image-service#152]
**1. the question: nydusd No such device **
**mkdir -p /opt/nydusd && cd /opt/nydusd && nydusify convert --nydus-image /usr/bin/nydus-image --source 192.168.1.130:8099/test/nginx:alpine --target 192.168.1.130:8099/test/nginx-nydus --source-insecure --target-insecure**
......
INFO[2021-08-21T18:42:45+08:00] [BLOB] Push blob                              Digest="sha256:1066684afa53a6c811caa6b22ae6c12431dd36ad8b12d98e214c935b6bb6a633" Size="1.9 kB" Time=29.101858ms
INFO[2021-08-21T18:42:45+08:00] [MANI] Push manifest                         
INFO[2021-08-21T18:42:45+08:00] [MANI] Push manifest                          Time=82.089513ms
INFO[2021-08-21T18:42:45+08:00] Converted to 192.168.1.130:8099/test/nginx-nydus
tree tmp -L 4
tmp
├── blobs
│   ├── 1066684afa53a6c811caa6b22ae6c12431dd36ad8b12d98e214c935b6bb6a633
│   ├── 4ee84c5b440641474cde5ebc7a1a146c377de72b71c43f8a4f57c5eea031296c
│   ├── 8c735009543a508adfc6e7986663d1f11343f2500ac89d3a32885aca8cd28ec0
│   ├── c440fd17d5dcda79d5cc45342b41e77c35a58e1ad2226998d06213acfa465d25
│   ├── ebc3c76be347ad99857f9b762d5ce3a320ba77a2441ce5f63b37110a3157a69d
│   └── faacfd1af225f32c5d748e2b4e4752a3e495e03d4937e3f27f659a298e98dce3
├── bootstraps
│   ├── 1-sha256:bc276c40b172b1c5467277d36db5308a203a48262d5f278766cf083947d05466
│   ├── 2-sha256:9fda960ad36a1e76f356412120e3d7d03b607d3d9962041c7269015af4b6a336
│   ├── 3-sha256:7336cfe0ea04876960d7ab5b6d16b8167185a00b4ac9e3f3ecdffad27d27b242
│   ├── 4-sha256:ad5643e92f173af5a47a05624dcc44e934ca174390bbb480ad66f902b5cd6443
│   ├── 5-sha256:9929dc79f45b709f6fdbf428c4f8ccd3b19e83543542cb9a5cdea8b3aa53766d
│   └── 6-sha256:c3554b2d61e3c1cffcaba4b4fa7651c644a3354efaafa2f22cb53542f6c600dc
├── output.json
└── source
**vi ./registry.json **
{
  "device": {
	"backend": {
	  "type": "registry",
	  "config": {
		"scheme": "http",
		"host": "192.168.1.130:8099",
		"repo": "/test/nginx:alpine"
	  }
	},
	"digest_validate": false
  },
  "mode": "direct"
}
**nydusd --config ./registry.json --mountpoint ./mnt --bootstrap ./tmp/bootstraps/6-sha256:c3554b2d61e3c1cffcaba4b4fa7651c644a3354efaafa2f22cb53542f6c600dc --log-level info**
[2021-08-21 19:08:12.111874 +08:00] INFO [utils/src/lib.rs:75] Git Commit: "5caf58755f5161e291230024343506584c8b4823", Build Time: "Mon, 22 Mar 2021 10:07:20 +0000", Profile: "release", Rustc Version: "rustc 1.49.0 (e1884a8e3 2020-12-29)"
[2021-08-21 19:08:12.112094 +08:00] INFO [rafs/src/metadata/mod.rs:235] rafs superblock features: COMPRESS_LZ4_BLOCK | DIGESTER_BLAKE3 | EXPLICIT_UID_GID
[2021-08-21 19:08:12.112163 +08:00] INFO [rafs/src/storage/backend/request.rs:147] backend config: CommonConfig { proxy: ProxyConfig { url: "", ping_url: "", fallback: true, check_interval: 5 }, timeout: 5, connect_timeout: 5, force_upload: false, retry_limit: 0 }
[2021-08-21 19:08:12.120556 +08:00] INFO [src/bin/nydusd/daemon.rs:410] Rafs imported
[2021-08-21 19:08:12.120634 +08:00] INFO [src/bin/nydusd/daemon.rs:329] rafs mounted at /
**Error: Os { code: 19, kind: Other, message: "No such device" }**

**2. configuration information**
**vi /etc/containerd/config.toml**
version = 2
root = "/var/lib/containerd"
state = "/run/containerd"
[proxy_plugins]
  [proxy_plugins.nydus]
    type = "snapshot"
    address = "/run/containerd/containerd-nydus-grpc.sock"
......
[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
	sandbox_image = "registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2"
	systemd_cgroup = true
	[plugins."io.containerd.grpc.v1.cri".containerd]
	  snapshotter = "nydus"
	  disable_snapshot_annotations = false
	  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
		[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
		  runtime_type = "io.containerd.runtime.v1.linux"
		  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
			SystemdCgroup = true
......

**vi /etc/nydusd-config.json**
{
    "device": {
        "backend": {
            "type": "registry",
            "config": {
                "scheme": "http",
                "host": "192.168.1.130:8099",
                "auth": "YWRtaW46SGFyYm9yMTIzNDU=",
                "timeout": 5,
                "connect_timeout": 5,
                "retry_limit": 0
            }
        },
        "cache": {
            "type": "blobcache",
            "compressed": true,
            "config": {
                "work_dir": "cache"
            }
        }
    },
    "mode": "direct",
    "digest_validate": false,
    "iostats_files": true,
    "enable_xattr": false,
    "fs_prefetch": {
        "enable": true,
        "threads_count": 10,
        "bandwidth_rate": 1048576
    }
}

**3. version information**
runc -v
runc version 1.0.0
commit: v1.0.0-0-g84113eef
spec: 1.0.2-dev
go: go1.15.14
libseccomp: 2.3.1

containerd -v
containerd github.com/containerd/containerd v1.4.8 7eba5930496d9bbe375fdf71603e610ad737d2b2

**4. service status**
**systemctl status containerd -l**
● containerd.service - containerd container runtime
   Loaded: loaded (/etc/systemd/system/containerd.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2021-08-21 19:07:12 CST; 1min 6s ago
     Docs: https://containerd.io
  Process: 704509 ExecStartPre=/sbin/modprobe overlay (code=exited, status=1/FAILURE)
 Main PID: 704513 (containerd)
    Tasks: 13
   Memory: 20.4M
   CGroup: /system.slice/containerd.service
           └─704513 /usr/local/bin/containerd

Aug 21 19:07:12 k8s-master containerd[704513]: time="2021-08-21T19:07:12.989712145+08:00" level=info msg=serving... address=/run/containerd/containerd.sock
Aug 21 19:07:12 k8s-master systemd[1]: Started containerd container runtime.
Aug 21 19:07:12 k8s-master containerd[704513]: time="2021-08-21T19:07:12.989779318+08:00" level=info msg="containerd successfully booted in 0.051927s"
Aug 21 19:07:12 k8s-master containerd[704513]: time="2021-08-21T19:07:12.991490838+08:00" level=warning msg="The image registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2 is not unpacked."
Aug 21 19:07:12 k8s-master containerd[704513]: time="2021-08-21T19:07:12.995067974+08:00" level=warning msg="The image registry.cn-hangzhou.aliyuncs.com/google_containers/pause@sha256:927d98197ec1141a368550822d18fa1c60bdae27b78b0c004f705f548c07814f is not unpacked."
Aug 21 19:07:12 k8s-master containerd[704513]: time="2021-08-21T19:07:12.998616376+08:00" level=warning msg="The image sha256:80d28bedfe5dec59da9ebf8e6260224ac9008ab5c11dbbe16ee3ba3e4439ac2c is not unpacked."
Aug 21 19:07:12 k8s-master containerd[704513]: time="2021-08-21T19:07:12.999379005+08:00" level=info msg="Start event monitor"
Aug 21 19:07:12 k8s-master containerd[704513]: time="2021-08-21T19:07:12.999403448+08:00" level=info msg="Start snapshots syncer"
Aug 21 19:07:12 k8s-master containerd[704513]: time="2021-08-21T19:07:12.999412718+08:00" level=info msg="Start cni network conf syncer"
Aug 21 19:07:12 k8s-master containerd[704513]: time="2021-08-21T19:07:12.999416308+08:00" level=info msg="Start streaming server

**5. snapshotter containerd-nydus-grpc**
**containerd-nydus-grpc --nydusd-path /usr/bin/nydusd --config-path /etc/nydusd-config.json --log-level trace --root /var/lib/containerd/io.containerd.snapshotter.v1.nydus --address /run/containerd/containerd-nydus-grpc.sock**

{"level":"info","msg":"found 0 daemons running","time":"2021-08-21T19:06:39.850981412+08:00"}

**Comment by liubogithub** [comment]
```
nydusd --config ./registry.json --mountpoint ./mnt --bootstrap ./tmp/bootstraps/6-sha256:c3554b2d61e3c1cffcaba4b4fa7651c644a3354efaafa2f22cb53542f6c600dc --log-level info
[2021-08-21 19:08:12.111874 +08:00] INFO [utils/src/lib.rs:75] Git Commit: "5caf58755f5161e291230024343506584c8b4823", Build Time: "Mon, 22 Mar 2021 10:07:20 +0000", Profile: "release", Rustc Version: "rustc 1.49.0 (e1884a8e3 2020-12-29)"
[2021-08-21 19:08:12.112094 +08:00] INFO [rafs/src/metadata/mod.rs:235] rafs superblock features: COMPRESS_LZ4_BLOCK | DIGESTER_BLAKE3 | EXPLICIT_UID_GID
[2021-08-21 19:08:12.112163 +08:00] INFO [rafs/src/storage/backend/request.rs:147] backend config: CommonConfig { proxy: ProxyConfig { url: "", ping_url: "", fallback: true, check_interval: 5 }, timeout: 5, connect_timeout: 5, force_upload: false, retry_limit: 0 }
[2021-08-21 19:08:12.120556 +08:00] INFO [src/bin/nydusd/daemon.rs:410] Rafs imported
[2021-08-21 19:08:12.120634 +08:00] INFO [src/bin/nydusd/daemon.rs:329] rafs mounted at /
Error: Os { code: 19, kind: Other, message: "No such device" }
```

This looks like an error in `fuse_kern_mount` where `FUSE_DEVICE` is not found.   

May I know if you run this on a Mac?  @844700118

**Comment by 844700118** [comment]
非常感谢, 这个问题得到解决  @xujihui1985  @liubogithub
