### ISSUE TITLE
build failed this function takes 2 arguments but 3 arguments were supplied

### ISSUE THREAD

**Issue by 844700118** [dragonflyoss/image-service#153]
**wget https://github.com/dragonflyoss/image-service/archive/refs/heads/master.zip**
**make && make release && make docker-static** 
......
 Compiling vhost v0.1.0 (https://github.com/cloud-hypervisor/vhost.git?branch=dragonball#42296415)
   Compiling micro_http v0.2.0 (https://hub.fastgit.org/cloud-hypervisor/micro-http.git?branch=master#f4405cb5)
   Compiling event-manager v0.2.0 (https://hub.fastgit.org/rust-vmm/event-manager.git?tag=v0.2.0#abac9289)
   Compiling vhost v0.1.0 (https://hub.fastgit.org/cloud-hypervisor/vhost.git?branch=dragonball#42296415)
   Compiling vm-virtio v0.1.0 (https://github.com/cloud-hypervisor/vm-virtio.git?branch=dragonball#cd0f7204)
   Compiling rand_chacha v0.3.1
**error[E0061]: this function takes 2 arguments but 3 arguments were supplied**
  --> /root/.cargo/git/checkouts/event-manager-e0a7f20e8f34fb60/abac928/src/epoll.rs:37:44
   |
37 |         let event_count = match self.epoll.wait(
   |                                            ^^^^ expected 2 arguments
38 |             self.ready_events.capacity(),
   |             ----------------------------
39 |             milliseconds,
   |             ------------
40 |             &mut self.ready_events[..],
   |             -------------------------- supplied 3 arguments

error: aborting due to previous error

For more information about this error, try `rustc --explain E0061`.
error: could not compile `event-manager`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [build-virtiofs] Error 101

rustc -V
rustc 1.50.0 (cb75ad5db 2021-02-10)

cargo -V
cargo 1.50.0 (f04e7fab7 2021-02-04)

**Comment by jiangliu** [comment]
这个是由于vmm-sys-util crate的一个breaking upgrade导致的，可以修改一下Cargo.toml锁定0.6版本。后续统一升级到0.8版本。
