### ISSUE TITLE
Fixes clippy errors

### ISSUE THREAD

**Issue by gaius-qi** [dragonflyoss/image-service#182]
Fixes clippy errors.

[actions](https://github.com/dragonflyoss/image-service/pull/181/checks?check_run_id=3754976621)

**Comment by changweige** [comment]
What rust tool chain are you based on? Nydus pins its rust tool chain to 1.52.1.
Otherwise, should me close this issue now?

**Comment by changweige** [comment]
I am closing this issue since a local test has proved that no clippy warnings are thrown out and it is inactive for some time.
