### ISSUE TITLE
zsh: exec format error: ./nydusify

### ISSUE THREAD

**Issue by valiantljk** [dragonflyoss/image-service#21]
compiled nydusify on mac with the following command:

`cd contrib/nydusify`
`make build-release`
`cd cmd`
`chmod +x nydusify`
`./nydusify convert --help`

**Comment by imeoer** [comment]
Hi @valiantljk, we have a specified target os platform to Linux in Makefile for compilation, so it failed to exec on the macOS. Nydusify is theoretically supported on all platforms, but we have not tested it on these.

**Comment by imeoer** [comment]
> I have a Macbook with M2 chip that uses arm64 arch and I'm not able to execute the *-linux-arm64 release and I get the same error.

@Aym3nTN What linux distribution are you using?

**Comment by Aym3nTN** [comment]
I used this release [nydus-static-v2.2.4-linux-arm64.tgz](https://github.com/dragonflyoss/nydus/releases/download/v2.2.4/nydus-static-v2.2.4-linux-arm64.tgz) and trying to make it work on macOS Sonoma 14.1
