### ISSUE TITLE
Support zstd compression algorithm in blob

### ISSUE THREAD

**Issue by liubogithub** [dragonflyoss/image-service#237]
zstd is a widely adopted compression algorithm, compared to lz4, it offers both speed and better compression ratio.

**Comment by hsiangkao** [comment]
Considering public network conditions (plus network laging) and our default 1MiB chunk size , IMO, zstd has more benefits than lz4.
Working on this within my extra time.

**Comment by liubogithub** [comment]
The related code is located at 
https://github.com/dragonflyoss/image-service/blob/d73e2711c6cbc1f1248dac683689cb93f3708707/src/bin/nydus-image/core/node.rs#L412
https://github.com/dragonflyoss/image-service/blob/d73e2711c6cbc1f1248dac683689cb93f3708707/utils/src/compress/mod.rs#L82

**Comment by liubogithub** [comment]
#388 has been merged.
Lets close this.
