### ISSUE TITLE
Support View method in nydus snapshotter

### ISSUE THREAD

**Issue by liubogithub** [dragonflyoss/image-service#239]
For now View doesn’t work as expected.

**Comment by changweige** [comment]
Thanks for reporting. I will fix this.

**Comment by bergwolf** [comment]
This should be moved to https://github.com/containerd/nydus-snapshotter now.

**Comment by changweige** [comment]
I closed this since a replacement now is added to https://github.com/containerd/nydus-snapshotter/issues/2
