### ISSUE TITLE
Snapshot's local directories are residual

### ISSUE THREAD

**Issue by changweige** [dragonflyoss/image-service#244]
As mentioned in PR #243 

> Discussed with @luodw offline, so the issue is that when we create more containers with the same image in non-shared daemon mode, we would create extra directories in WithSocketDir and WithConfigDir etc., which is a side effect of failing fs.manager.NewDaemon(d). Defly a bug and need to be fixed.

**Comment by bergwolf** [comment]
Already fixed by #243
