### ISSUE TITLE
Move images annotations that need to be passed to snapshotter  to snapshotter repo

### ISSUE THREAD

**Issue by changweige** [dragonflyoss/image-service#264]
Nydus-snapshotter is being migrated from this repo to containerd organization.
Right now, nydus-snapshotter depends on nydusify for using those image annotations.
Those annotations' names is prefixed with `containerd.io/snapshot`, which will all be passed to snapshotter by containerd.

So better we move those annotations' definition to snapshotter

**Comment by liubogithub** [comment]
Is this work done yet?

**Comment by imeoer** [comment]
@liubogithub not yet, but it's not a high priority.

**Comment by adamqqqplay** [comment]
Finished in https://github.com/containerd/nydus-snapshotter/pull/351
Upstream related: https://github.com/containerd/containerd/pull/8036 and https://github.com/moby/moby/pull/44810
