### ISSUE TITLE
The blobs annotation in manifest should be deprecated

### ISSUE THREAD

**Issue by imeoer** [dragonflyoss/image-service#268]
Reference: https://github.com/containerd/nydus-snapshotter/issues/5

**Comment by bergwolf** [comment]
Can we have a replacement that still enables us to get the blob list statically? It is a bit heavy to run nydusd just to get the blob list. I understand that nydus-snapshotter can do it via nydusd, I'm more thinking about static analysis of nydus images.

**Comment by imeoer** [comment]
An alternative is to use the static inspect tool, for example:

```
$ nydus-image inspect --bootstrap ~/bootstrap -R blobs                                                                                                                     
[{"blob_id":"x","compressed_size":0,"decompressed_size":0,"readahead_offset":0,"readahead_size":0}]
```

**Comment by luodw** [comment]
I have an idea, maybe we can add another blob layer xxx, it contains annotation "containerd.io/snapshot/nydus-blob-ids=true". When create container, snapshot find nydus meta layer and blob_ids layer in the meantime
 in func `findNydusMetaLayer` so as to reduse find overhead.

**Comment by imeoer** [comment]
@luodw The blob layer should exist on [manifest](https://github.com/dragonflyoss/image-service/blob/7f3efa78ae3af27fbc4a0c7364672d0005ae8f56/contrib/nydusify/examples/manifest/manifest.json#L10) if using the registry as blob storage backend, so the blobs annotation is mainly used on referencing the blobs stored on another storage backend (for example oss).

**Comment by luodw** [comment]
> we

@imeoer I known, I mean we can add blob ids_list layer to manifest just like meta layer.  So it can also download from storage backend and unpack.

**Comment by imeoer** [comment]
@luodw Ok, I see your point, but I don't think it's necessary to have the blob list as a layer entity, if we do that, the snapshotter needs to handle it additionally, which would be a more complicated change for nydus format.

**Comment by changweige** [comment]
@imeoer  Shall we close this now since the label has been dropped from nydus image and related PR has been merged

**Comment by imeoer** [comment]
@changweige Ok, thanks for solving the issue.
