### ISSUE TITLE
Unify fusedev and virtiofs frontend

### ISSUE THREAD

**Issue by changweige** [dragonflyoss/image-service#299]
Two nydus runtime binaries are produced when release. One is for fusedev frontend while the other one is for virtiofs.
When nydus is working as vitriofs daemon when supply kata containers with rootfs, users have to deploy those two binaries in the same server. It brings up chaos and blur to end users.
It's better to let nydus be configure to work as FUSE daemon or virtiofs daemon.

**Comment by jiangliu** [comment]
We need to enhance the fuse-backend-rs first, to support fusedev and virtiofs concurrently.

**Comment by imeoer** [comment]
cc @uran0sH is tracking and resolving this issue, thanks!

**Comment by jiangliu** [comment]
done

**Comment by adamqqqplay** [comment]
Finished in #743
