### ISSUE TITLE
Crate non-x86 releases

### ISSUE THREAD

**Issue by liubin** [dragonflyoss/image-service#300]
Now release only provides x86_64 binaries, aarch64 is also needed.

Related to https://github.com/kata-containers/tests/issues/4445

**Comment by bergwolf** [comment]
It seems that github action doesn't provide non-x86_64 build platform. The only supported way is to use self-hosted aarch64 machines but we don't have aarch64 hosts. Any suggestions?

**Comment by liubin** [comment]
Another choice is to build from source for aarch64.

**Comment by bergwolf** [comment]
Yes, Kata can build it from source for non-x86 platforms.

**Comment by bergwolf** [comment]
FYI, we have aarch64 and x86_64 binaries now. See https://github.com/dragonflyoss/image-service/releases/tag/v2.0.0-rc.5
