### ISSUE TITLE
Optimize bootstrap size for rafs v6

### ISSUE THREAD

**Issue by hsiangkao** [dragonflyoss/image-service#348]
For now, bootstrap sizes of nydus rafs v6 are still far worse than the sizes of what erofs-utils generates.
We should support effective tail-packing inline with a real block allocator for rafs v6 nydus, see:
https://git.kernel.org/pub/scm/linux/kernel/git/xiang/erofs-utils.git/tree/lib/cache.c

**Comment by liubogithub** [comment]
@pigletDips is working on it.
