### ISSUE TITLE
Handle std::io::Error::Interrupted from mio::poll()

### ISSUE THREAD

**Issue by jiangliu** [dragonflyoss/image-service#362]
If some signal get delivered during calling mio::poll(), it will return `Err(std::io::Error::Interrupted)`. We should handle this case to retry poll again.

**Comment by jiangliu** [comment]
@killagu could you please help take a look at this issue?

**Comment by bergwolf** [comment]
It is already handled. One thing we can improve is to exit the loop when non EINTR is returned by mio poll. See https://github.com/dragonflyoss/image-service/pull/371
