### ISSUE TITLE
switch nydus-cached to mio

### ISSUE THREAD

**Issue by bergwolf** [dragonflyoss/image-service#366]
Right now `nydus-cached` is the only one left using `event_manager`. We can switch it to mio and drop `event_manager` dependency.

**Comment by uran0sH** [comment]
If no one works on it, I would like to work on it.

**Comment by liubogithub** [comment]
@uran0sH Wenyu, thanks so much for taking it.

**Comment by bergwolf** [comment]
@uran0sH Are you still working on it?

**Comment by uran0sH** [comment]
I am busy for preparing the final exam, so I have no time to work on it.
