### ISSUE TITLE
[nydus-snapshotter] run container err when use SingleInstance

### ISSUE THREAD

**Issue by luodw** [dragonflyoss/image-service#37]
I follow https://github.com/dragonflyoss/image-service/blob/master/docs/containerd-env-setup.md to test nydus-snapshotter. When I not use --shared-daemon, it will run ok. but when i use --shared-daemon, it will run failed. 

error is shown as bellow
![image](https://user-images.githubusercontent.com/14847074/103616738-f2489180-4f67-11eb-9318-1ad158b97863.png)

**Comment by bergwolf** [comment]
@luodw could you start nydus-snapshotter with `--log-level debug` and see if there are logs about `shared_daemon`? I wonder if nydusd is running.

**Comment by luodw** [comment]
@bergwolf it shows that miss required arguments
![image](https://user-images.githubusercontent.com/14847074/103735761-b8d85a80-5029-11eb-86dc-b18c2e3bc411.png)

**Comment by changweige** [comment]
Regarding to `shared daemon` mode, nydus-snapshotter requests Nydus daemon to mount through HTTP API.
From what I can see from current code base, the API is no longer compatible. So this is very likely the reason why this issue happened. Sorry for the trouble. I will sync related code to upstream to make it work. Before that, please use the the other mode to start container.
Thanks for your report.

**Comment by Apokleos** [comment]
I have the same problem!!!
```
# crictl run container-config.yaml pod-config.yaml
FATA[0002] running container: creating container failed: rpc error: code = Unknown desc = failed to create containerd container: failed to mount daemon l0JTKuDlToWhljpjLV-0fQ: failed to shared mount: failed to mount: stat /var/lib/containerd/io.containerd.snapshotter.v1.nydus/socket/shared_daemon/api.sock: no such file or directory: unknown
```

**Comment by bergwolf** [comment]
@luodw @Apokleos This should have been fixed with current master. Please reopen if you see it again. Thanks!
