### ISSUE TITLE
Nydusd starts failed with fuse

### ISSUE THREAD

**Issue by Apokleos** [dragonflyoss/image-service#41]
I do it as the offical docs!

Steps as below:
1. I have successfully convert ubuntu:18.04 docker image to Nydus format image;
2. the ubutu:18.04-nydus located at current dir tmp/ as:
```
[root@hah nydus-dev]# tree tmp/ -L 2
tmp/
├── localhost:5000
│   └── ubuntu:18.04-nydus
└── ubuntu:18.04
    ├── manifest.json
    ├── sha256:3cf8fb62ba5ffb221a2edb2208741346eb4d2d99a174138e4afbb69ce1fd9966
    ├── sha256:e80c964ece6a3edf0db1cfc72ae0e6f0699fb776bbfcc92b708fbb945b0b9547
    └── sha256:f22ccc0b8772d8e1bcb40f137b373686bc27427a70c0e41dd22b38016e09e7e0

6 directories, 1 file

and ububtu:18.04-nydus
[root@hah nydus-dev]# tree tmp/localhost\:5000/ -L 2
tmp/localhost:5000/
└── ubuntu:18.04-nydus
    ├── blobs
    ├── bootstrap
    ├── bootstrap-parent
    ├── config.json
    └── manifest.json

2 directories, 4 files
```

3.  localfs.json as below:
```
[root@hah nydus-dev]# cat localfs.json
{
  "device": {
    "backend": {
      "type": "localfs",
      "config": {
        "dir": "./tmp/localhost:5000/ubuntu:18.04-nydus/blobs"
       }
    }
  },
  "mode": "direct"
}
```
4. Run nydusd daemon with FUSE.  I have compiled nydus with rustc-1.47.0 and run the shell as below:
```
[root@hah nydus-dev]# ../image-service/target-fusedev/debug/nydusd --config localfs.json --mountpoint ./mnt/ --bootstrap tmp/localhost\:5000/ubuntu\:18.04-nydus/bootstrap --log-level trace
2021-01-18T03:25:00+00:00 - INFO - rafs superblock features: COMPRESS_LZ4_BLOCK DIGESTER_BLAKE3 EXPLICIT_UID_GID HAS_XATTR
2021-01-18T03:25:00+00:00 - INFO - rafs imported
2021-01-18T03:25:00+00:00 - INFO - rafs mounted: mode=direct digest_validate=false iostats_files=false
2021-01-18T03:25:00+00:00 - DEBUG - pseudo fs mount iterate "/"
2021-01-18T03:25:00+00:00 - TRACE - fuse: vfs fs_idx 1 inode 1 fuse ino 0x100000000000001
2021-01-18T03:25:00+00:00 - TRACE - fs_idx 1 inode 1
2021-01-18T03:25:00+00:00 - INFO - vfs mounted
2021-01-18T03:25:00+00:00 - INFO - mount source nydusfs dest /root/RustProjects/dragonflyoss/nydus-dev/mnt with fstype fuse opts default_permissions,allow_other,fd=8,rootmode=40000,user_id=0,group_id=0 fd 8
2021-01-18T03:25:00+00:00 - INFO - starting fuse daemon

2021-01-18T03:25:00+00:00 - TRACE - fuse: new req Init: InHeader { len: 56, opcode: 26, unique: 2, nodeid: 0, uid: 0, gid: 0, pid: 0, padding: 0 }
2021-01-18T03:25:00+00:00 - INFO - FUSE INIT major 7 minor 31
 in_opts: ASYNC_READ | POSIX_LOCKS | ATOMIC_O_TRUNC | EXPORT_SUPPORT | BIG_WRITES | DONT_MASK | SPLICE_WRITE | SPLICE_MOVE | SPLICE_READ | FLOCK_LOCKS | HAS_IOCTL_DIR | AUTO_INVAL_DATA | DO_READDIRPLUS | READDIRPLUS_AUTO | ASYNC_DIO | WRITEBACK_CACHE | ZERO_MESSAGE_OPEN | PARALLEL_DIROPS | HANDLE_KILLPRIV | POSIX_ACL | ABORT_ERROR | MAX_PAGES | CACHE_SYMLINKS | ZERO_MESSAGE_OPENDIR | EXPLICIT_INVAL_DATA
out_opts: ASYNC_READ | ATOMIC_O_TRUNC | BIG_WRITES | HAS_IOCTL_DIR | AUTO_INVAL_DATA | DO_READDIRPLUS | READDIRPLUS_AUTO | ASYNC_DIO | WRITEBACK_CACHE | ZERO_MESSAGE_OPEN | PARALLEL_DIROPS | MAX_PAGES | CACHE_SYMLINKS | ZERO_MESSAGE_OPENDIR | EXPLICIT_INVAL_DATA
2021-01-18T03:25:00+00:00 - TRACE - fuse: new reply OutHeader { len: 80, error: 0, unique: 2 }
2021-01-18T03:25:01+00:00 - WARN - read fuse dev failed on fd 13: EINVAL: Invalid argument
2021-01-18T03:25:01+00:00 - INFO - nydusd quits
```
5.  pick out the error message as below
```
...
2021-01-18T03:25:01+00:00 - WARN - read fuse dev failed on fd 13: EINVAL: Invalid argument
....
```
How to solve it ?
Thank you !

**Comment by bergwolf** [comment]
@Apokleos what is the kernel version that you are running?

**Comment by Apokleos** [comment]
> @Apokleos what is the kernel version that you are running?

I have tried on both CentOS8 with kerner version 4.18.0-193.19.1.el8_2.x86_64 and Fedora33 with version 5.9.10-200.fc33.x86_64, and got the same error!

**Comment by bergwolf** [comment]
>  in_opts: ASYNC_READ | POSIX_LOCKS | ATOMIC_O_TRUNC | EXPORT_SUPPORT | BIG_WRITES | DONT_MASK | SPLICE_WRITE | SPLICE_MOVE | SPLICE_READ | FLOCK_LOCKS | HAS_IOCTL_DIR | AUTO_INVAL_DATA | DO_READDIRPLUS | READDIRPLUS_AUTO | ASYNC_DIO | WRITEBACK_CACHE | ZERO_MESSAGE_OPEN | PARALLEL_DIROPS | HANDLE_KILLPRIV | POSIX_ACL | ABORT_ERROR | MAX_PAGES | CACHE_SYMLINKS | ZERO_MESSAGE_OPENDIR | EXPLICIT_INVAL_DATA
out_opts: ASYNC_READ | ATOMIC_O_TRUNC | BIG_WRITES | HAS_IOCTL_DIR | AUTO_INVAL_DATA | DO_READDIRPLUS | READDIRPLUS_AUTO | ASYNC_DIO | WRITEBACK_CACHE | ZERO_MESSAGE_OPEN | PARALLEL_DIROPS | MAX_PAGES | CACHE_SYMLINKS | ZERO_MESSAGE_OPENDIR | EXPLICIT_INVAL_DATA

The feature bits look good. It's unclear what when wrong. CI is running `4.15.0-1037-gcp` and I run `4.19` locally. At least I don't expect `4.18.0` to be broken in between. Let me find an environment and try to reproduce.

**Comment by Apokleos** [comment]
> > in_opts: ASYNC_READ | POSIX_LOCKS | ATOMIC_O_TRUNC | EXPORT_SUPPORT | BIG_WRITES | DONT_MASK | SPLICE_WRITE | SPLICE_MOVE | SPLICE_READ | FLOCK_LOCKS | HAS_IOCTL_DIR | AUTO_INVAL_DATA | DO_READDIRPLUS | READDIRPLUS_AUTO | ASYNC_DIO | WRITEBACK_CACHE | ZERO_MESSAGE_OPEN | PARALLEL_DIROPS | HANDLE_KILLPRIV | POSIX_ACL | ABORT_ERROR | MAX_PAGES | CACHE_SYMLINKS | ZERO_MESSAGE_OPENDIR | EXPLICIT_INVAL_DATA
> > out_opts: ASYNC_READ | ATOMIC_O_TRUNC | BIG_WRITES | HAS_IOCTL_DIR | AUTO_INVAL_DATA | DO_READDIRPLUS | READDIRPLUS_AUTO | ASYNC_DIO | WRITEBACK_CACHE | ZERO_MESSAGE_OPEN | PARALLEL_DIROPS | MAX_PAGES | CACHE_SYMLINKS | ZERO_MESSAGE_OPENDIR | EXPLICIT_INVAL_DATA
> 
> The feature bits look good. It's unclear what when wrong. CI is running `4.15.0-1037-gcp` and I run `4.19` locally. At least I don't expect `4.18.0` to be broken in between. Let me find an environment and try to reproduce.

I have test on my debian10 with kernel 4.19.x and it works well. 
But, I find that the kernel 4.19.x using FUSE API version 7.27, while kernel 5.9.x using FUSE API version 7.31 (CentOS8 kernel 4.18 using FUSE API 7.31 too). So, I guess the FUSE API's difference may cause the failure. 
When I upgrade my debian10's kernel to kernel 5.9 and run the nydusd, the failure same as the issue description occures.

**Comment by bergwolf** [comment]
@Apokleos Thanks for the info! It helps a lot. I'll look at newer kernel changes and see what caused the problem.

**Comment by Apokleos** [comment]
Thanks @bergwolf , I have tested on my fedora33 with 5.9.x, and it  works smoothly now.

**Comment by bergwolf** [comment]
Thanks for confirming that @Apokleos !
