### ISSUE TITLE
avoid the extra duplicated chunk info table in bootstrap

### ISSUE THREAD

**Issue by liubogithub** [dragonflyoss/image-service#414]
In order to support chunk dict, Nydus v6 format now incorporates `chunk info ` table at the end of bootstrap (for more details, check [HERE](https://github.com/dragonflyoss/image-service/blob/21f5e49d44b3f482aa11ab8f290204428a822290/src/bin/nydus-image/core/bootstrap.rs#L670)), though nydus v6 format's blob already has a simplified  version of `chunk info` (w/o chunk digest).

Since it's not ideal, here might be a better approach,
1. separate chunk info table into a single file, i.e. `image.chunks`
2. while building an image, pack both `image.boot` and `image.chunks`into the TAR layer
3. mark this TAR layer as `nydus-blob` annotation so that nydus-snapshotter's `Prepare` is able to skip downloading it
4. make nydus-snapshotter to download the `image.boot`.

With the above, we not only support chunk dict (with a bit changes for sure), but avoid the extra duplicated chunk info table in bootstrap.

**Comment by jiangliu** [comment]
It's really great if we could split out the blob chunk, which is only needed when:
1) data validation is enabled
2) build image

**Comment by jiangliu** [comment]
For step 4, how could we choose to only download the image.boot from the tar file, skipping the image.chunk?

**Comment by imeoer** [comment]
> For step 4, how could we choose to only download the image.boot from the tar file, skipping the image.chunk?

My understanding is that the `image.chunk` is placed the tail of tar stream, so we can close the http connection once the `image.boot` is downloaded.

**Comment by hsiangkao** [comment]
> > For step 4, how could we choose to only download the image.boot from the tar file, skipping the image.chunk?
> 
> My understanding is that the `image.chunk` is placed the tail of tar stream, so we can close the http connection once the `image.boot` is downloaded.

we can follow what stargz did as Gzip(tar(image.boot)) + Gzip(tar(image.chunk)), so image.boot can be fetched in advance.

**Comment by jiangliu** [comment]
> > > For step 4, how could we choose to only download the image.boot from the tar file, skipping the image.chunk?
> > 
> > 
> > My understanding is that the `image.chunk` is placed the tail of tar stream, so we can close the http connection once the `image.boot` is downloaded.
> 
> we can follow what stargz did as Gzip(tar(image.boot)) + Gzip(tar(image.chunk)), so image.boot can be fetched in advance.

we are still lacking of two things here:
1) a mechanism to identify the range of Gzip(tar(image.boot)) and Gzip(tar(image.chunk))
2) a mechanism to store hash value of Gzip(tar(image.boot)) and Gzip(tar(image.chunk))

**Comment by hsiangkao** [comment]
> > > > For step 4, how could we choose to only download the image.boot from the tar file, skipping the image.chunk?
> > > 
> > > 
> > > My understanding is that the `image.chunk` is placed the tail of tar stream, so we can close the http connection once the `image.boot` is downloaded.
> > 
> > 
> > we can follow what stargz did as Gzip(tar(image.boot)) + Gzip(tar(image.chunk)), so image.boot can be fetched in advance.
> 
> we are still lacking of two things here:
> 
> 1. a mechanism to identify the range of Gzip(tar(image.boot)) and Gzip(tar(image.chunk))
> 2. a mechanism to store hash value of Gzip(tar(image.boot)) and Gzip(tar(image.chunk))

1. we don't need to get the range in advance unless we're going to use multithread download approach, but I think in that way, we don't need to get the range as well, since we can download in 2M or whatever unit, and decompress bulks in order when available. 
2. just 2 sha256 hash, it's not hard.
