### ISSUE TITLE
add support for rafsv6 in nydusify

### ISSUE THREAD

**Issue by liubogithub** [dragonflyoss/image-service#425]
At this moment, nydusify can only do conversion from OCIv1 image to rafsv5 image, conversion from OCIv1 image to rafsv6 image needs to be supported as well.

[acceld](https://github.com/goharbor/acceleration-service) provides the required functionality, so maybe we can share the same golang package with nydusify?

**Comment by imeoer** [comment]
Supported in https://github.com/dragonflyoss/image-service/pull/473, thanks @zyfjeff  @yawqi
