### ISSUE TITLE
RFE: enhance nydus-image/nydusify check to do full filesystem check

### ISSUE THREAD

**Issue by eryugey** [dragonflyoss/image-service#435]
Currently "nydus-image check" sub-command only checks if the converted image is in valid rafs format, and doesn't do full filesystem integrity check.

We'd better to enhance nydus-image check to do full filesystem integrity check without mounting rafs.

**Comment by imeoer** [comment]
1.  `nydusify check` need to check `dev, rdev, symlink, project id, uid, gid, nlink, ctime` between source image and nydus image.
2. currently `nydusify check` only checks filesystem data (chunks) if the user provides `--backend-type registry` and `--backend-config ...`, we need to remove this limitation (e.g. automatically read registry auth from docker config).
3. currently `nydusify check` requires docker to be installed (for pulling source image and mounting all layers by overlayfs), we need to remove this limitation, pull, unpack and mount image layer by nydusify self.
4. `nydusify check` provides `--source-type directory` or `--source-type tar` parameter to support code package filesystem consistency check.

**Comment by adamqqqplay** [comment]
Finished in #543
