### ISSUE TITLE
blob gc feature for fscache with ``inuse`` and ``cull``

### ISSUE THREAD

**Issue by hsiangkao** [dragonflyoss/image-service#454]
We should implement these to avoid too many unused cachefiles.

also see, https://github.com/lostjeffle/demand-read-cachefilesd/blob/main/test/test13-daemon.c

**Comment by hsiangkao** [comment]
@nan1994 @imeoer
please help discuss these interfaces in order to make the gc functionality work.

**Comment by adamqqqplay** [comment]
It is also discussed in https://github.com/containerd/nydus-snapshotter/pull/262
