### ISSUE TITLE
fork/exec /path/to/nydus-image: permission denied

### ISSUE THREAD

**Issue by laowenyi** [dragonflyoss/image-service#465]
when i execute command
sudo /data/nydus-static/nydusify convert --nydus-image /path/to/nydus-image --source hub.site/test/nginx:v1.1 --target hub.site/test/nginx:v1.3

fork/exec /path/to/nydus-image: permission denied

**Comment by imeoer** [comment]
The `nydus-image` is a binary file, would you make `chmod +x /path/to/nydus-image` ?

**Comment by liubogithub** [comment]
@laowenyi Did `chmod +x` helps?

**Comment by liubogithub** [comment]
No response for over a month.
