### ISSUE TITLE
Support image conversion for nerdctl

### ISSUE THREAD

**Issue by imeoer** [dragonflyoss/image-service#475]
Convert an OCI image to nydus image like:

```
nerdctl image convert --nydus --oci ghcr.io/ubuntu:oci ghcr.io/ubuntu:nydus
```

We can use the [Converter](https://github.com/containerd/nydus-snapshotter/blob/main/pkg/converter/convert_unix.go) package.

**Comment by imeoer** [comment]
cc @loheagn can help to do this.

**Comment by changweige** [comment]
@imeoer Should close this since nertctl has merged nydus support?
