### ISSUE TITLE
failed in the containerd-env-setup experiment

### ISSUE THREAD

**Issue by xunwumizhi** [dragonflyoss/image-service#48]
when I test containerd with nydus-snapshotter as the doc of this repository below:
https://github.com/dragonflyoss/image-service/blob/master/docs/containerd-env-setup.md

I have convert a nydus style image using:
`nydusify convert --nydus-image /usr/local/bin/nydus-image --source docker.io/library/ubuntu:16.04 --target localhost:5000/ubuntu:16.04-nydus`
and then the image was pushed into my local registry, I can find it:
```
>> curl "http://localhost:5000/v2/ubuntu/tags/list"
{"name":"ubuntu","tags":["16.04-nydus"]}
```

But, after I started `nydus-snapshotter` and `containerd`, I want to use `crictl` test the whole process:
`crictl pull localhost:5000/ubuntu:16.04-nydus`
`crictl` error happend, message:
```
FATA[0000] pulling image: rpc error: code = Unknown desc = failed to pull and unpack image "localhost:5000/ubuntu:16.04-nydus": failed to prepare extraction snapshot "extract-262457039-f1jQ sha256:6df557218c153a61f8d1901eb213a80413b18a6f789c9ed0b5bef6d3ec9e3679": failed to find image ref of snapshot 25, labels map[containerd.io/snapshot.ref:sha256:6df557218c153a61f8d1901eb213a80413b18a6f789c9ed0b5bef6d3ec9e3679 containerd.io/snapshot/nydus-bootstrap:true]: unknown 
```

the `nydus-snapshotter` error message:
```
{"dir":"/var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/25","level":"info","msg":"cleanupSnapshotDirectory /var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/25","time":"2021-01-21T16:53:35.285184694+08:00"}

{"dir":"/var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/25","error":"failed to get daemon by snapshotID (25)","level":"error","msg":"failed to unmount","time":"2021-01-21T16:53:35.285204313+08:00"}

{"level":"info","msg":"umount nydus daemon of id 25, mountpoint /var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/25","time":"2021-01-21T16:53:35.285217642+08:00"}

{"dir":"/var/lib/containerd/io.containerd.snapshotter.v1.nydus/snapshots/25","error":"failed to get daemon by snapshotID (25)","level":"error","msg":"failed to unmount","time":"2021-01-21T16:53:35.285231057+08:00"}
........
```

`nydus-snapshotter` settings:
```
containerd-nydus-grpc --nydusd-path /usr/local/bin/nydusd     --config-path /etc/nydusd-config.json     --shared-daemon     --log-level debug     --root /var/lib/containerd/io.containerd.snapshotter.v1.nydus     --address /run/containerd/containerd-nydus-grpc.sock       --nydusimg-path /usr/local/bin/nydus-image
```

how to understand the problem and solve it?

**Comment by bergwolf** [comment]
Thanks for the report. There is a known issue in the `--shared-daemon` mode. Please remove it from the `nydus-snapshotter` settings and retry.

I've raised https://github.com/dragonflyoss/image-service/pull/49 to alter the setup guide as well.

**Comment by xunwumizhi** [comment]
> Thanks for the report. There is a known issue in the `--shared-daemon` mode. Please remove it from the `nydus-snapshotter` settings and retry.
> 
> I've raised #49 to alter the setup guide as well.


Great!

**Comment by xunwumizhi** [comment]
> Thanks for the report. There is a known issue in the `--shared-daemon` mode. Please remove it from the `nydus-snapshotter` settings and retry.
> 
> I've raised #49 to alter the setup guide as well.

Great ! 
I remove the `--shared-daemon` arg of `nydus-snapshotter`  
AND set the `containerd` config file just keep the same as written in the doc (not modified the file got from `containerd config default > /etc/containerd/config.toml` ):

```
```
