### ISSUE TITLE
An idea to standardize Nydus blobs

### ISSUE THREAD

**Issue by hsiangkao** [dragonflyoss/image-service#485]
So that each Nydus blob (including bootstrap) are all tar format:

1. bootstrap.tar includes
/d7y_nydus/fs.meta
/d7y_nydus/[blobid].blob.meta (optional, (e)stargz mandatory)
/d7y_nydus/[blobid].blob.chunkdigest (optional, (e)stargz mandatory)
...

2. each rafs.blob.tar includes
/d7y_nydus/[blobid].blob
/d7y_nydus/[blobid].blob.meta
/d7y_nydus/[blobid].blob.chunkdigest
...

3. (e)stargz.blob.tar includes
stargz + TOC

So that
1) Nydus images can be directly pulled by Docker.
2) If a Nydus image is directly run by Docker or stargz_snapshotter, rafs bootstrap and blob tars are treated as extra layers, so some /d7y_nydus directory will occur, and we could hook and remount the docker/stargz_snapshotter mergedir + nydus blobs as the final mergedir.
3) (e)stargz + Nydus can be run by stargz_snapshotter and nydus_snapshotter.

And in that case, we could also merge bootstrap + blobs as
4. merged rafs blob
/d7y_nydus/fs.meta
/d7y_nydus/[blobid].blob
/d7y_nydus/[blobid].blob.meta
/d7y_nydus/[blobid].blob.chunkdigest
for buildkit or runtime for example.

**Comment by jiangliu** [comment]
Interesting! We could use [Descriptor](https://github.com/opencontainers/image-spec/blob/main/descriptor.md) annotations to encode `(compressed offset, compressed size, uncompressed size)` for each tar object, then we could download needed data on-demand.

**Comment by jiangliu** [comment]
How about something like this?
![截屏2022-06-12 下午11 43 16](https://user-images.githubusercontent.com/1931516/173241360-ce3c90f1-dbe0-4f6a-9bb1-3d2e6aeb0984.png)

**Comment by hsiangkao** [comment]
close this one due to https://github.com/dragonflyoss/image-service/issues/873
