### ISSUE TITLE
nydusify: append fs version annotation in image manifest

### ISSUE THREAD

**Issue by imeoer** [dragonflyoss/image-service#496]
We need to add an annotation to the image manifest for detecting the bootstrap fs version without reading the magic number from bootstrap, example:

```
"containerd.io/snapshot/nydus-bootstrap": "true",
"containerd.io/snapshot/nydus-fs-version": "6",
...
```

**Comment by hsiangkao** [comment]
I tend to leave this optional, both ways are ok to us.
