### ISSUE TITLE
can't find nydusd binary in release page

### ISSUE THREAD

**Issue by aa624545345** [dragonflyoss/image-service#502]
In release page, i downloaded nydus-static-v2.0.0-linux-amd64.tgz, but i can't find nydusd binary.
where should i find nydusd, thx.
$ ls
configs  ctr-remote  nydus-cached  nydusctl  nydusd-fusedev  nydusd-virtiofs  nydus_graphdriver  nydusify  nydus-image  nydus-overlayfs

**Comment by imeoer** [comment]
Sorry for the confusion, nydusd currently has two binaries, `nydusd-fusedev` (for fuse daemon mode) and `nydusd-virtiofs` (for virtiofs daemon mode), you can use `nydusd-fusedev` directly.

If you are interested, please help to update the doc, thanks!

**Comment by imeoer** [comment]
Thanks! fixed in https://github.com/dragonflyoss/image-service/pull/505
