### ISSUE TITLE
Add description about nydus support in nerdctl doc

### ISSUE THREAD

**Issue by imeoer** [dragonflyoss/image-service#555]
https://github.com/containerd/nerdctl/blob/master/README.md

At least we can add some description in nerdctl doc about lazy pulling with nydus snapshotter.

**Comment by hsiangkao** [comment]
I'm not sure if Nerdctl maintainers like it since only stargz is shown in its doc.

**Comment by AkihiroSuda** [comment]
> I'm not sure if Nerdctl maintainers like it since only stargz is shown in its doc.

I like :+1:

**Comment by hsiangkao** [comment]
> > I'm not sure if Nerdctl maintainers like it since only stargz is shown in its doc.
> 
> I like 👍

Thanks a lot Akihiro Suda! We're trying our best to form an approach for Nydus, estargz and more ;)

**Comment by hsiangkao** [comment]
Hi @loheagn , would you mind adding little description about nydus as a follow-up of https://github.com/containerd/nerdctl/pull/1163 . Many thanks in advance!

**Comment by loheagn** [comment]
> Hi @loheagn , would you mind adding some description about nydus as a follow-up of [containerd/nerdctl#1163](https://github.com/containerd/nerdctl/pull/1163) . Many thanks in advance!

No problem. You can assign this issue to me.

**Comment by hsiangkao** [comment]
> > Hi @loheagn , would you mind adding some description about nydus as a follow-up of [containerd/nerdctl#1163](https://github.com/containerd/nerdctl/pull/1163) . Many thanks in advance!
> 
> No problem. You can assign this issue to me.

I heard that @imeoer is already on that :) Sorry for bothering, his version is almost done, we could comment the version then... thanks again!

**Comment by jiangliu** [comment]
Closed via https://github.com/containerd/nerdctl/pull/1189
