### ISSUE TITLE
More optimizations for estargz

### ISSUE THREAD

**Issue by hsiangkao** [dragonflyoss/image-service#559]
I observe many possible optimization points for estargz lazy pulling, such as:
  1) pull estargz TOCs in parallel;
  2) further investigation / improvements of estargz chunk lazy pulling;
  3) we need to support estargz prioritize files;
  4) convert all estargz TOCs to RAFS v6 bootstrap in advance as bootstrap and ship as a whole;

**Comment by jiangliu** [comment]
This should have already fixed by read amplification on master branch.
