### ISSUE TITLE
I have a question about the data deduplication between different images.

### ISSUE THREAD

**Issue by aa624545345** [dragonflyoss/image-service#560]
it says in `nydus-design.md` ,  'Chunk level data deduplication'. 
But in my operation, it seems that no deduplication happens beteen two images that store one same file.

The image bash3 and image busybox3 store one same file named 2.mp4.
```bash
[root@]# docker images
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
127.0.0.1:5000/bash3             latest              42d6acc28ca1        35 minutes ago      217 MB
127.0.0.1:5000/busybox3          latest              3b9f14494344        35 minutes ago      206 MB
```
Size of 2.mp4 is 195M.
```bash
[root@]# du -sh ./*
195M	./2.mp4
```
I push these two images to registry, and convert them to nydus format using the command below:
```bash
nydusify convert --nydus-image /usr/local/bin/nydus-image --source localhost:5000/busybox3 --target localhost:5000/busybox3-nydus
nydusify convert --nydus-image /usr/local/bin/nydus-image --source localhost:5000/bash3 --target localhost:5000/bash3-nydus
```
use `ctr-remote image rpull` to pull this two nydus format images down, and use `nerdctl` to run container with this two images:
```bash
ctr-remote image rpull --plain-http 127.0.0.1:5000/busybox3-nydus:latest
ctr-remote image rpull --plain-http 127.0.0.1:5000/bash3-nydus:latest

nerdctl --snapshotter nydus run --rm -it 127.0.0.1:5000/busybox3-nydus sh
nerdctl --snapshotter nydus run --rm -it 127.0.0.1:5000/bash3-nydus sh
```

however, in cache file, it looks like no deduplication happens:
```bash
[root@ nydus]# pwd
/var/lib/nydus
[root@ nydus]# du -sh cache
404M	cache
[root@ cache]# du -sh ./*
1.2M	./36c56a37eae123e85121cd61beb0687ee0533fecc030eb3a5618354c840e28a1
8.0K	./36c56a37eae123e85121cd61beb0687ee0533fecc030eb3a5618354c840e28a1.chunk_map
**195M	./56c8d5a9a2a2c7e7942d5e4cc0b2ef7b1f39bab50d49e36c2d6ca53773e90392**
8.0K	./56c8d5a9a2a2c7e7942d5e4cc0b2ef7b1f39bab50d49e36c2d6ca53773e90392.chunk_map
7.0M	./6334bc6fa88956e1027d6e9259f026b463211f03c561c2017b970746cc8c1e37
8.0K	./6334bc6fa88956e1027d6e9259f026b463211f03c561c2017b970746cc8c1e37.chunk_map
4.0K	./bff60b60d8ee71479e3d6fff2f581435c857bf2596bc62fe445d8f6f4919a55c
8.0K	./bff60b60d8ee71479e3d6fff2f581435c857bf2596bc62fe445d8f6f4919a55c.chunk_map
5.4M	./d542d4a146037df4e940d6921f0e16e9e0307ea60090e71281655c16ce048f8a
8.0K	./d542d4a146037df4e940d6921f0e16e9e0307ea60090e71281655c16ce048f8a.chunk_map
**195M	./e003d8fac6f2abf567249084bcadfed5b987af7072e7ec970a90cea9c35907a8**
8.0K	./e003d8fac6f2abf567249084bcadfed5b987af7072e7ec970a90cea9c35907a8.chunk_map
```

**Comment by hsiangkao** [comment]
Hi @aa624545345, thanks for the question.

AFAIK, `Chunk-based data deduplication` means it will de-duplicate the same chunk among blobs (layers) when building the image.

There is another CAS called local or node CAS which we're currently working on it to replace OSTree approach as a finer chunk-based local content-addressable storage. Also see, https://lore.kernel.org/all/YqZNJpgQ+xLSHBqK@debian/

Cc: @bergwolf @jiangliu

**Comment by jiangliu** [comment]
There are several levels of chunk deduplication:
1) within a image layer
2) within all layers of current image
3) within all layers of current image and referenced images
4) within all layers of all images on local node

1 and 2 are supported by default. 
For 3, you need to add parameter "parent-bootstrap" to nydus-image when generating the image.
For 4, we are designing an node local content storage subsystem for node local chunk deduplication.

**Comment by aa624545345** [comment]
Thank you for your answers.☺ @jiangliu @hsiangkao
