### ISSUE TITLE
Rafs v6 mount is consuming more time than v5

### ISSUE THREAD

**Issue by changweige** [dragonflyoss/image-service#561]
Mount Rafs v6 has to fetch chunk info metadata from the storage backend for each layer/blob one by one sequentially, which Rafs v5 does not have to do. It means a container image with more layers will have a slower mount. 
Better we can improve it since mount does not need chunk infos.

**Comment by hsiangkao** [comment]
In the short term, we could delay blob.meta fetching to the first blob read. Thus it will avoid unnecessary blob.metas.

In the mid term, see https://github.com/dragonflyoss/image-service/issues/485 , each blob.meta can be with bootstrap.tar or  blob itself.

**Comment by hsiangkao** [comment]
According to
https://github.com/dragonflyoss/image-service/issues/587#issuecomment-1181273278

Time-consuming may not be due to blob.meta fetching one by one. Yet it's still worth optimizing..

**Comment by jiangliu** [comment]
Now v6 should have identical performance with v5.
