### ISSUE TITLE
Nydusify converting Rafs v6 image costs nearly double time then v5

### ISSUE THREAD

**Issue by changweige** [dragonflyoss/image-service#565]
Source image python:3.7  stored in an internal reigstry, which means network bandwidth is not a limitation.
Target registry is a locally running docker registry:2.

```
nydusify convert --nydus-image ../nydus-image --work-dir ../nydusify_work_dir --source hub.xxx.org/gechangwei/python:3.7 --target 127.0.0.1:5000/nydus/python:3.7_converted --fs-version 6 --docker-v2-format
```

Rafs V5 Image conversion time including Pull and Push , Takes time 14.346 seconds
Rafs V6 Image conversion time including Pull and Push , Takes time 30.128 seconds

**Comment by changweige** [comment]
> how about the current status of `acceld` to convert?
26 seconds
![image](https://user-images.githubusercontent.com/23294915/177535159-1de4e0c6-5da6-408e-8797-6dd47a72af77.png)

**Comment by hsiangkao** [comment]
> > how about the current status of `acceld` to convert?
> > 26 seconds
> > ![image](https://user-images.githubusercontent.com/23294915/177535159-1de4e0c6-5da6-408e-8797-6dd47a72af77.png)

how about v5 with `acceld`?
Anyway I think it's a runtime stuff only and need to be investigated

**Comment by hsiangkao** [comment]
it seems we need another load_parent() for v6 since EROFS don't maintain the parent inode number for each inode (consider hard link cases). We can just use DFS way to generate fs tree.

**Comment by changweige** [comment]
Sorry I messed up `acceld` configuraion:

For v6: 27 secs
![image](https://user-images.githubusercontent.com/23294915/177561337-49e3774a-9c18-491d-a328-bbdb56680e55.png)

For v5: 14 secs

![image](https://user-images.githubusercontent.com/23294915/177563221-e5aba3f4-3574-42c2-a1ac-ff4249788540.png)


However, it seemed that `acceld` failed pusing manifest to registry

```
ERRO[2022-07-06T21:34:54.909575072+08:00] convert in worker: push image: failed commit on ref "manifest-sha256:c718004ac4887b5507ed89a3c19e73e3723734ced02db6c1d5fe94bd3af734d0": cannot reuse body, request must be retried
```

**Comment by changweige** [comment]
> it seems we need another load_parent() for v6 since EROFS don't maintain the parent inode number for each inode (consider hard link cases). We can just use DFS way to generate fs tree.
> 
> It should have similar performance with the current parent inode link way.

Do you think it is the cause why v6 conversion is slower?

**Comment by hsiangkao** [comment]
> > it seems we need another load_parent() for v6 since EROFS don't maintain the parent inode number for each inode (consider hard link cases). We can just use DFS way to generate fs tree.
> > It should have similar performance with the current parent inode link way.
> 
> Do you think it is the cause why v6 conversion is slower?

not quite sure, I think we should find a way to perf the path? any perference for rust program?

**Comment by imeoer** [comment]
Post my test result:

| image     | tool     | fs version | time |
| --------- | -------- | ---------- | ---- |
| wordpress | acceld*   | v6         | 16s  |
| wordpress | acceld*   | v5         | 13s  |
| wordpress | nydusify | v6         | 24s  |
| wordpress | nydusify | v5         | 15s  |
| python    | acceld*   | v6         | 23s  |
| python    | acceld*   | v5         | 22s  |
| python    | nydusify | v6         | 26s  |
| python    | nydusify | v5         | 21s  |

`*` acceld uses [converter](https://github.com/goharbor/acceleration-service/pull/45) implementation, not diff build.

> However, it seemed that acceld failed pusing manifest to registry
`ERRO[2022-07-06T21:34:54.909575072+08:00] convert in worker: push image: failed commit on ref "manifest-sha256:c718004ac4887b5507ed89a3c19e73e3723734ced02db6c1d5fe94bd3af734d0": cannot reuse body, request must be retried`

@changweige Not sure about this, are there any further tests?

**Comment by jiangliu** [comment]
Seems we need to optimize nydusify, anyone working on this topic?

**Comment by imeoer** [comment]
@jiangliu `Nydusify` conversion workflow is layer by layer, but `acceld` conversion layer is concurrent (via the converter package) and we will migrate nydusify to converter as well in the future.

**Comment by changweige** [comment]
> @jiangliu `Nydusify` conversion workflow is layer by layer, but `acceld` conversion layer is concurrent (via the converter package) and we will migrate nydusify to converter as well in the future.

But it seems nydusify and acceld takes nearly the same time

**Comment by changweige** [comment]
> Seems we need to optimize nydusify, anyone working on this topic?

We should delve into those `nydus-image` result output.json and compare each step elapse between v5 and v6. IOW, we still need more analysis input.

**Comment by jiangliu** [comment]
With the latest master branch, there's no big difference between v5 and v6 build time:
![截屏2022-11-12 17 47 19](https://user-images.githubusercontent.com/1931516/201468563-5e25f67f-8d31-4a46-97ee-25328c2e39f2.png)
