### ISSUE TITLE
nydusify can't parse local `/etc/hosts` when push images

### ISSUE THREAD

**Issue by changweige** [dragonflyoss/image-service#585]
My DNS server does not have a record of the registry host name. So I put the host name - IP mapping in the `/etc/hosts`, however, nydusify **can‘t** use the info there while nerdctl/containerd and acceld can. Nyduisy still tries to lookup registry IP from my DNS server

**Comment by liubogithub** [comment]
Besides this, nydusify also does not support a registry which has self signed certificate.

We'll fix it together.

**Comment by changweige** [comment]
> Besides this, nydusify also does not support a registry which has self signed certificate.
> 
> We'll fix it together.

Cool 👍

**Comment by changweige** [comment]
I tested the recent master code nydusify. The problem is gone. Closing it
