### ISSUE TITLE
[help] run Nydusd daemon with error, what argument is invalid?

### ISSUE THREAD

**Issue by zhangshuiyong** [dragonflyoss/image-service#586]
I use nydusd-fusedev to run Nydusd daemon, but occur an error like that, what argument is invalid?

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/1655233/178248183-9727638d-17ee-4458-9440-543c15bb00fc.png">

**nydusd-fusedev version:**
<img width="430" alt="image" src="https://user-images.githubusercontent.com/1655233/178247994-1f841cfc-fbc6-4ff5-a306-bebf84bc9e2e.png">

**change config file like that after read the [doc/nydusd.md](https://github.com/dragonflyoss/image-service/blob/master/docs/nydusd.md):**

<img width="499" alt="image" src="https://user-images.githubusercontent.com/1655233/178248717-a1cd4fc9-616c-4f26-933d-58037a4380d3.png">

**argument Dir like that:**
<img width="362" alt="image" src="https://user-images.githubusercontent.com/1655233/178249128-351e1d0f-1833-4e9d-bbcc-d6dc001bdf9f.png">

**note: i use "touch bootstrap" command to create that empty file(bootstrap), is that ok?**

**run Command:**

./nydusd-fusedev --config /home/cpu6/zhangshuiyong/nydus-static/configs/config-localfs-host.json --mountpoint /home/cpu6/zhangshuiyong/nydusmount --bootstrap /home/cpu6/zhangshuiyong/nydusrafsbootstrap/bootstrap --log-level info

**Comment by imeoer** [comment]
Thanks for reporting, seems it is caused by the empty bootstrap file, you can try this to create bootstrap/blobs file:

```
nydus-image create --bootstrap /path/to/bootstrap --blob-dir /path/to/blob/dir /path/to/source-dir
```

Indeed the nydusd error log is confusing for users, we are trying to improve it. https://github.com/dragonflyoss/image-service/issues/121

**Comment by liubogithub** [comment]
No response from the author for 2 weeks, close it for now.
