### ISSUE TITLE
Nerdctl runs V6 nydus image slower than running V5 nydus image

### ISSUE THREAD

**Issue by changweige** [dragonflyoss/image-service#587]
I ran [HelloBench](https://github.com/Tintri/hello-bench) container startup benchmark tool and the result follows.
Nydusd `prefetch-all` is disabled.

This might relate to https://github.com/dragonflyoss/image-service/issues/561

### nydus v5
```json
{"repo": "python:3.7-nydus-v5", "bench": "python:3.7-nydus-v5", "elapsed": 5.305230379104614}
```

### nydus v6
```
{"repo": "python:3.7-nydus-v6", "bench": "python:3.7-nydus-v6", "elapsed": 6.725706100463867}
```

### OCI
```
{"repo": "python:3.7", "bench": "python:3.7", "elapsed": 10.794086456298828}
```

**Comment by changweige** [comment]
I also made a comparison between nydusd v1.1.2 and master code. The result follows:

This time I enabled `prefetch_all`

1.1.2
```json
{"repo": "python:3.7-nydus-v5", "bench": "python:3.7-nydus-v5", "elapsed": 0.7368912696838379}
```

master
```json
{"repo": "python:3.7-nydus-v5", "bench": "python:3.7-nydus-v5", "elapsed": 5.696261405944824}
```

**Comment by changweige** [comment]
I added instrument code around blob meta downloading.
From the printed message, the official python container image takes **27.88ms** to download the meta of each layer.
It looks that the meta downloading is not that time-consuming.


```
[2022-07-12 10:37:29.778080 +08:00] ERROR [storage/src/device.rs:846] Elapsed: 27.88ms
```


```rust
impl BlobDevice {
    /// Create new blob device instance.
    pub fn new(
        config: &Arc<FactoryConfig>,
        blob_infos: &[Arc<BlobInfo>],
    ) -> io::Result<BlobDevice> {
        let mut blobs = Vec::with_capacity(blob_infos.len());

        use std::time::Instant;

        let now = Instant::now();

        for blob_info in blob_infos.iter() {
            let blob = BLOB_FACTORY.new_blob_cache(config, blob_info)?;
            blobs.push(blob);
        }

        let elapsed = now.elapsed();
        warn!("Elapsed: {:.2?}", elapsed);

        Ok(BlobDevice {
            blobs: ArcSwap::new(Arc::new(blobs)),
            blob_count: blob_infos.len(),
        })
    }

```

**Comment by liubogithub** [comment]
@changweige Did you run nydus v6 fuse mode?

Seems that prefetch doesn't work with multi threads, can you please confirm if it's multi thread prefetch?

**Comment by changweige** [comment]
> Did you run nydus v6 fuse mode?

Yes.

> Seems that prefetch doesn't work with multi threads, can you please confirm if it's multi thread prefetch?

It has 4 prefetch threads setup

```
  "mode": "direct",
  "digest_validate": false,
  "enable_xattr": true,
  "fs_prefetch": {
    "enable": true,
    "prefetch_all": true,
    "threads_count": 4,
    "merging_size": 0,
    "bandwidth_rate": 0
  },

```

**Comment by jiangliu** [comment]
#610 tries to solve this issue

**Comment by jiangliu** [comment]
Should have been fixed by https://github.com/dragonflyoss/image-service/pull/626.
