### ISSUE TITLE
Error: invalid bootstrap, seems have multiple non-chunk-dict blobs in this bootstrap

### ISSUE THREAD

**Issue by weishenmezhememan** [dragonflyoss/image-service#594]
When I execute the following command：
./nydus-image merge --bootstrap ./ bootstrap-split/image/image1.boot bootstrap-split/image/image.boot
image1.boot and image.boot（bootstrap） are obtained from registry storage， with dir like：
/opt/docker/registry-nydus-diff/docker/registry/v2/blobs/sha256/15/15a2fedda8342e527312825f38a17fef4fffde584cf62fb082aeedc5a841646e/data

There is an error message：
[2022-07-14 18:41:37.201305 +08:00] INFO [rafs/src/metadata/md_v5.rs:28] rafs superblock features: COMPRESS_LZ4_BLOCK | DIGESTER_BLAKE3 | EXPLICIT_UID_GID | HAS_XATTR
Error: invalid bootstrap, seems have multiple non-chunk-dict blobs in this bootstrap

How to correctly merge the bootstrap files of two images？

**Comment by imeoer** [comment]
Hi @weishenmezhememan how these bootstraps built? `nydus-image merge` command only support to merge the bootstrap created by `nydus-image create --inline-bootstrap` command.

**Comment by weishenmezhememan** [comment]
Well, I have a requirement to reduce the volume occupied by all images in the registry. I learned that Nydus supports the same layer and cross layer multiplexing of the same image, as well as the multiplexing of two images (specified by the "--parent-bootstrap referenced image-bootstrap" parameter). I originally intended to merge the bootstrap of all images to achieve the maximum de duplication effect. Or, please guide how to complete the data De duplication between multiple images

**Comment by liubogithub** [comment]
> Well, I have a requirement to reduce the volume occupied by all images in the registry. I learned that Nydus supports the same layer and cross layer multiplexing of the same image, as well as the multiplexing of two images (specified by the "--parent-bootstrap referenced image-bootstrap" parameter). I originally intended to merge the bootstrap of all images to achieve the maximum de duplication effect. Or, please guide how to complete the data De duplication between multiple images

@weishenmezhememan 
I think the followings should work for your case, take image A as the base image,
1. use nydusify convert image A to image A-nydus,
2. use nydusify convert image B to image B-nydus but with `nydusify --chunk-dict /path/to/A-image.boot`

step 2 offers the data dedup between image B and image A.

**Comment by weishenmezhememan** [comment]
thanks. This is a two mirror de duplication, which I have tried before, and it is feasible. But I need to find a scheme to remove the duplicate of multiple images (maybe dozens of images), that is, when I convert the n+1 image, I can remove the duplicate as long as the files or data blocks in the previous n images appear. More guidance?

**Comment by liubogithub** [comment]
Hmm, I don't think there is a one-stop solution for this.

But what we've tried is,
1. convert all oci images to nydus images,
2. analysis these nydus images with `nydus-image inspect`and dump all used chunks out,
3. find out the dup chunks from it and make a base image from these dup chunks,
4. convert all oci images again to nydus images _with_ the base image.

FYI.

**Comment by liubogithub** [comment]
No response for 2 weeks, close it for now.
Will reopen it if needed.
