### ISSUE TITLE
How to pronounce nydus?

### ISSUE THREAD

**Issue by jongwu** [dragonflyoss/image-service#607]
Please forgive me. It's a stupid question. 
I'm new to nydus and it's confused me that how to pronounce nydus. Is there a official pronunciation?

**Comment by hsiangkao** [comment]
I pronounce it as `nYdəs` personally.

**Comment by liubogithub** [comment]
@jongwu Thanks for your interest.  
Nydus comes from one of Starcraft's zerg structures, implying `a box which moves things fast`, and it matches our goal of transferring data fast exactly.


w.r.t. pronunciation, it's N+`English/aɪdəs`, the first half of `Ni-ce` and the middle part of `In-dus-try`.
