### ISSUE TITLE
Nydusify can't convert OCI image with a big file to nydus image

### ISSUE THREAD

**Issue by yixiaojie0x** [dragonflyoss/image-service#662]
I tried to convert the OCI image ubuntu_fio:oci to nydus v6 image, which has a single 5G file 
fio_test_image in it. 

> root@xxx-xxx-xxx:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/4/fs/root# du * -sh
5.1G    fio_test_image

I used nydusify to convert it with

> time ./nydusify convert  --source hub.xxx.org/nydus_io_test/ubuntu_fio:oci   --target localhost:5000/ubuntu_fio:nydus_v6   --nydus-image /home/yixiaojie/image-service/target/debug/nydus-image   --work-dir ../nydusify_work_dir   --fs-version 6

And I got  a panic, here comes the info
> INFO[2022-08-09T10:41:11+08:00] Version: 846cc9f1f8010aad47fb49806fd5ece7ca656202.20220808.1020 
INFO[2022-08-09T10:41:11+08:00] Parsing image hub.byted.org/nydus_io_test/ubuntu_fio:oci 
INFO[2022-08-09T10:41:11+08:00] Converting to localhost:5000/ubuntu_fio:nydus_v6 
INFO[2022-08-09T10:41:12+08:00] [SOUR] Mount layer                            Digest="sha256:c5ec52c98b3193052e15d783aca2bef10d8d829fa0d58fedfede511920b8f997" Size="75 MB"
INFO[2022-08-09T10:41:12+08:00] [SOUR] Mount layer                            Digest="sha256:d933381eb13674378341a78f73f55a89432cde50779a839d532ea2546c39480c" Size="5.4 GB"
INFO[2022-08-09T10:41:13+08:00] [SOUR] Mount layer                            Digest="sha256:c5ec52c98b3193052e15d783aca2bef10d8d829fa0d58fedfede511920b8f997" Size="75 MB" Time=1.02757099s
INFO[2022-08-09T10:41:13+08:00] [DUMP] Build layer                            Digest="sha256:c5ec52c98b3193052e15d783aca2bef10d8d829fa0d58fedfede511920b8f997" Size="75 MB"
INFO[2022-08-09T10:41:18+08:00] [DUMP] Build layer                            Digest="sha256:c5ec52c98b3193052e15d783aca2bef10d8d829fa0d58fedfede511920b8f997" Size="75 MB" Time=5.391367132s
INFO[2022-08-09T10:41:18+08:00] [BOOT] Push bootstrap                         Digest="sha256:c5ec52c98b3193052e15d783aca2bef10d8d829fa0d58fedfede511920b8f997" Size="598 kB"
INFO[2022-08-09T10:41:19+08:00] [BOOT] Push bootstrap                         Digest="sha256:c5ec52c98b3193052e15d783aca2bef10d8d829fa0d58fedfede511920b8f997" Size="598 kB" Time=90.942331ms
INFO[2022-08-09T10:41:19+08:00] [BLOB] Push blob                              Digest="sha256:b8cdd32b9b759ec011e10c5c54cb7cde15fb72d4fe4a749f6ee29fc65025176a" Size="41 MB"
INFO[2022-08-09T10:41:19+08:00] [BLOB] Push blob                              Digest="sha256:b8cdd32b9b759ec011e10c5c54cb7cde15fb72d4fe4a749f6ee29fc65025176a" Size="41 MB" Time=3.302548ms
INFO[2022-08-09T10:42:24+08:00] [SOUR] Mount layer                            Digest="sha256:d933381eb13674378341a78f73f55a89432cde50779a839d532ea2546c39480c" Size="5.4 GB" Time=1m12.001969528s
INFO[2022-08-09T10:42:24+08:00] [DUMP] Build layer                            Digest="sha256:d933381eb13674378341a78f73f55a89432cde50779a839d532ea2546c39480c" Size="5.4 GB"
[2022-08-09 10:49:44.302621 +08:00] ERROR [/home/yixiaojie/.cargo/registry/src/github.com-1ecc6299db9ec823/log-panics-2.1.0/src/lib.rs:130] thread 'main' panicked at 'attempt to multiply with overflow': src/bin/nydus-image/core/node.rs:371
   0: <backtrace::capture::Backtrace as core::default::Default>::default
             at /home/yixiaojie/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:410:9
   1: log_panics::Config::install_panic_hook::{{closure}}
             at /home/yixiaojie/.cargo/registry/src/github.com-1ecc6299db9ec823/log-panics-2.1.0/src/lib.rs:115:29
   2: std::panicking::rust_panic_with_hook
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:702:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:586:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
   5: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   6: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   7: core::panicking::panic
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:48:5
   8: nydus_image::core::node::Node::dump_blob
             at /data00/home/yixiaojie/image-service/src/bin/nydus-image/core/node.rs:371:34
   9: nydus_image::core::blob::Blob::dump
             at /data00/home/yixiaojie/image-service/src/bin/nydus-image/core/blob.rs:41:32
  10: <nydus_image::builder::directory::DirectoryBuilder as nydus_image::builder::Builder>::build::{{closure}}
             at /data00/home/yixiaojie/image-service/src/bin/nydus-image/builder/directory.rs:163:17
  11: nydus_image::trace::trace_timing
             at /data00/home/yixiaojie/image-service/src/bin/nydus-image/trace.rs:90:13
  12: <nydus_image::builder::directory::DirectoryBuilder as nydus_image::builder::Builder>::build
             at /data00/home/yixiaojie/image-service/src/bin/nydus-image/builder/directory.rs:161:27
  13: nydus_image::Command::create::{{closure}}
             at /data00/home/yixiaojie/image-service/src/bin/nydus-image/main.rs:719:17
  14: nydus_image::trace::trace_timing
             at /data00/home/yixiaojie/image-service/src/bin/nydus-image/trace.rs:90:13
  15: nydus_image::Command::create
             at /data00/home/yixiaojie/image-service/src/bin/nydus-image/main.rs:717:28
  16: nydus_image::main
             at /data00/home/yixiaojie/image-service/src/bin/nydus-image/main.rs:587:9
  17: core::ops::function::FnOnce::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
  18: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:122:18
  19: std::rt::lang_start::{{closure}}
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:145:18
  20: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:20
  21: std::rt::lang_start
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:144:17
  22: main
  23: __libc_start_main
             at /build/glibc-77giwP/glibc-2.24/csu/../csu/libc-start.c:291
  24: _start
ERRO[2022-08-09T10:49:44+08:00] fail to run /home/yixiaojie/image-service/target/debug/nydus-image [create --parent-bootstrap ../nydusify_work_dir/bootstraps/1-sha256:c5ec52c98b3193052e15d783aca2bef10d8d829fa0d58fedfede511920b8f997 --bootstrap ../nydusify_work_dir/bootstraps/2-sha256:d933381eb13674378341a78f73f55a89432cde50779a839d532ea2546c39480c --log-level warn --whiteout-spec oci --output-json ../nydusify_work_dir/bootstraps/2-sha256:d933381eb13674378341a78f73f55a89432cde50779a839d532ea2546c39480c-output.json --blob ../nydusify_work_dir/blobs/be09aa7a-1521-4dbb-977a-b4baca8650a3 --fs-version 6 --prefetch-policy fs ../nydusify_work_dir/source/sha256:a6887a4e5a41cb874f3deea4b4b1c8deef5cf48d992a209f24caa640bca3dad6]  error="exit status 101"
INFO[2022-08-09T10:49:44+08:00] [DUMP] Build layer                            Digest="sha256:d933381eb13674378341a78f73f55a89432cde50779a839d532ea2546c39480c" Size="5.4 GB" Time=7m19.812013291s
FATA[2022-08-09T10:49:44+08:00] Failed to convert: Build source layer: Build source layer sha256:d933381eb13674378341a78f73f55a89432cde50779a839d532ea2546c39480c: build layer ../nydusify_work_dir/source/sha256:a6887a4e5a41cb874f3deea4b4b1c8deef5cf48d992a209f24caa640bca3dad6: exit status 101 
real    8m33.629s
user    7m13.597s
sys     0m23.769s

It seems nydus v6 cannot deal with that case.
Also, I tried to convert this OCI image to nydus v5, but I have got the same error.

**Comment by changweige** [comment]
I suppose it could be a fatal problem. 🥺 @imeoer Do you have any idea on this issue?

**Comment by zyfjeff** [comment]
@yixiaojie0x You seem to be using the debug version of nydus-image. Frankly speaking, this has not been tested and covered. Could you please help test the release version of nydus-image? In addition, can you provide your image address?

**Comment by zyfjeff** [comment]
```
            let chunk_size = blob_ctx.chunk_size;
            let file_offset = i as u64 * chunk_size as u64;
            let uncompressed_size = if i == self.inode.child_count() - 1 {
                (self.inode.size() as u64)
                    .checked_sub((chunk_size * i) as u64)
                    .ok_or_else(|| {
                        anyhow!("the rest chunk size of inode is bigger than chunk_size")
                    })? as u32
            } else {
                chunk_size
            };

```
 .checked_sub((chunk_size * i) as u64) ->  .checked_sub(chunk_size as u64 * I)  try it ? @yixiaojie0x

**Comment by imeoer** [comment]
@zyfjeff @yixiaojie0x Thanks for the report, it's my fault, fixed it in https://github.com/dragonflyoss/image-service/pull/663.
