### ISSUE TITLE
nydus-image inspect panic

### ISSUE THREAD

**Issue by bergwolf** [dragonflyoss/image-service#705]
> ./target-fusedev/debug/nydus-image inspect -B tests/texture/bootstrap/nydusd_daemon_test_bootstrap -R ls
    22       ""
    23       ""
[2022-08-30 15:04:21.043566 +08:00] ERROR [/home/graymalkin/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/log-panics-2.1.0/src/lib.rs:130] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ExecError
(File "" is not a child of CWD)': src/bin/nydus-image/main.rs:788
   0: <backtrace::capture::Backtrace as core::default::Default>::default
             at /home/graymalkin/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/backtrace-0.3.66/src/capture.rs:410:9
   1: log_panics::Config::install_panic_hook::{{closure}}
             at /home/graymalkin/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/log-panics-2.1.0/src/lib.rs:115:29
   2: std::panicking::rust_panic_with_hook
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:702:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:588:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
   5: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   6: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   7: core::result::unwrap_failed
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
   8: core::result::Result<T,E>::unwrap
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1078:23
   9: nydus_image::Command::inspect
             at src/bin/nydus-image/main.rs:788:21
  10: nydus_image::main
             at src/bin/nydus-image/main.rs:568:9
  11: core::ops::function::FnOnce::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:122:18
  13: std::rt::lang_start::{{closure}}
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:145:18
  14: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:20
  15: std::rt::lang_start
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:144:17
  16: main
  17: __libc_start_main
             at /build/glibc-uZu3wS/glibc-2.27/csu/../csu/libc-start.c:310
  18: _start

**Comment by bergwolf** [comment]
Still panics after applying https://github.com/cloud-hypervisor/fuse-backend-rs/pull/90

**Comment by YushuoEdge** [comment]
Seems like the entry point for this bootstrap is not root directory:
```
$ ./target/debug/nydus-image inspect -B tests/texture/bootstrap/nydusd_daemon_test_bootstrap
[2022-09-15 00:36:39.753038 +08:00] INFO [rafs/src/metadata/md_v5.rs:30] rafs superblock features: COMPRESS_NONE
Inspecting Rafs :> stat .
Inode Number:       1
Name:               ""
Size:               1
Parent:             0
Mode:               0x0
Permissions:        0
Nlink:              2
UID:                0
GID:                16877
Mtime:              0
MtimeNsec:          0
Blocks:             8
```

**Comment by imeoer** [comment]
Seems `tests/texture/bootstrap/nydusd_daemon_test_bootstrap` is a broken bootstrap file, maybe try `tests/texture/bootstrap/image_v2.boot`.

**Comment by bergwolf** [comment]
> Seems tests/texture/bootstrap/nydusd_daemon_test_bootstrap is a broken bootstrap file, maybe try tests/texture/bootstrap/image_v2.boot.

It is used at https://github.com/dragonflyoss/image-service/blob/master/src/bin/nydusd/fs_service.rs#L305, which ends up calling `rafs.import`. Why do you think it is a broken bootstrap file?

**Comment by imeoer** [comment]
> It is used at https://github.com/dragonflyoss/image-service/blob/master/src/bin/nydusd/fs_service.rs#L305, which ends up calling rafs.import. Why do you think it is a broken bootstrap file?

`rafs.import` just only load superblock section, if we check this bootstrap with `nydus-image check --bootstrap tests/texture/bootstrap/nydusd_daemon_test_bootstrap -V`, will fail with a invalid inode digest error:

```
[2022-09-15 07:26:53.872264 +00:00] INFO [rafs/src/metadata/md_v5.rs:30] rafs superblock features: COMPRESS_NONE
[2022-09-15 07:26:53.872668 +00:00] ERROR [rafs/src/metadata/layout/v5.rs:1412] invalid inode digest af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262, expected fa9fc870971e23b035a829756f6fe6ef325403c3400b02a5e988f884856b072a, ino: 1 name: ""
[2022-09-15 07:26:53.872731 +00:00] ERROR [error/src/error.rs:21] Error:
	"invalid inode digest"
	at rafs/src/metadata/direct_v5.rs:375
	note: enable `RUST_BACKTRACE=1` env to display a backtrace
Error: failed to check bootstrap "tests/texture/bootstrap/nydusd_daemon_test_bootstrap"
```

And indeed it's not a directory type inode.

**Comment by bergwolf** [comment]
Ok, fair enough. @xujihui1985 do you recall how the test bootstrap file (`tests/texture/bootstrap/nydusd_daemon_test_bootstrap`) was created? It was added by your commit 3e091ef52f3f1be479b2c9e4fbc3a3d962dfa16d

**Comment by jiangliu** [comment]
Seems it's caused by invalid "nydusd_daemon_test_bootstrap".
