### ISSUE TITLE
Support registry mirror configuration for registry backend

### ISSUE THREAD

**Issue by imeoer** [dragonflyoss/image-service#724]
See the point 3 at https://github.com/dragonflyoss/image-service/issues/716#issuecomment-1248915349

**Comment by changweige** [comment]
@imeoer Looks this can be closed now since the feature has been merged.

**Comment by imeoer** [comment]
@changweige Waiting nydus-snapshotter to support it.

**Comment by changweige** [comment]
nydus-snapshotter has already supported configured registry mirror by filling `mirrors:{}` in nydusd's config file

**Comment by imeoer** [comment]
Ok, let's track the progress of snapshotter in https://github.com/containerd/nydus-snapshotter/issues/51
