### ISSUE TITLE
create container failed for a Ready sandbox

### ISSUE THREAD

**Issue by zvier** [dragonflyoss/image-service#727]
Create container failed for a Ready sandbox when use nydus. The error message is:

```
FATA[0001] creating container: rpc error: code = Unknown desc = failed to create containerd container: failed to wait shared daemon: wait until daemon ready by checking status: failed to check status: failed to create new nydus client: failed to build transport for nydus client: stat /media/disk1/containerd/io.containerd.snapshotter.v1.nydus/socket/shared_daemon/api.sock: no such file or directory: unknown
```
And the containerd-nydus-grpc log print 
```
INFO[2022-09-16T17:52:25.662572514+08:00] prepare remote snapshot mountpoint /media/disk1/containerd/io.containerd.snapshotter.v1.nydus/snapshots/2/fs
WARN[2022-09-16T17:52:25.662591983+08:00] daemon daemon_id=shared_daemon is not found
WARN[2022-09-16T17:52:25.662731917+08:00] daemon daemon_id=shared_daemon is not found
INFO[2022-09-16T17:52:25.663951747+08:00] start nydus daemon: /usr/bin/nydusd fuse --mountpoint /media/disk1/containerd/io.containerd.snapshotter.v1.nydus/mnt --apisock /media/disk1/containerd/io.containerd.snapshotter.v1.nydus/socket/shared_daemon/api.sock --log-level info
error: Found argument 'fuse' which wasn't expected, or isn't valid in this context

USAGE:
    nydusd [FLAGS] [OPTIONS] --mountpoint <mountpoint>

For more information try --help
```
The related yaml file is:

## nydus-sandbox.yaml
```
metadata:
  attempt: 1
  name: nydus-sandbox-1
  namespace: default
log_directory: /tmp
linux:
  security_context:
    namespace_options:
      network: 2
annotations:
  "io.containerd.osfeature": "nydus.remoteimage.v1"
```

## nydus-container.yaml
```
metadata:
  name: nydus-container
image:
  image: cloud-native-sig-registry.cn-hangzhou.cr.aliyuncs.com/openanolis/anolisos:8.6-x86_64-nydus
command:
  - /bin/sleep
args:
  - 600
log_path: container.1.log
```

```
crictl pull cloud-native-sig-registry.cn-hangzhou.cr.aliyuncs.com/openanolis/anolisos:8.6-x86_64-nydus
pod=`crictl runp nydus-sandbox.yaml`
container=`crictl create $pod nydus-container.yaml nydus-sandbox.yaml`
crictl start $container
crictl ps
```

The nydus version infomation is:
`nydus-static-v2.1.0-rc.2-linux-arm64.tgz`

`containerd-nydus-grpc` is build myself.

**Comment by changweige** [comment]
What commit version of `containerd-nydus-grpc` did you build on?

**Comment by jiangliu** [comment]
Could you please help to share the output of:
/usr/bin/nydusd -h 
/usr/bin/nydusd --version

**Comment by zvier** [comment]
> What commit version of `containerd-nydus-grpc` did you build on?

The latest commit `0f88fb6a4f190c01bab42aba2bd47aca784546c2`

**Comment by zvier** [comment]
> Could you please help to share the output of: /usr/bin/nydusd -h /usr/bin/nydusd --version

/usr/bin/nydusd -h
```
Version: 	2.0.0
Git Commit: 	1c0598e87dab207286c31ab4cab3025092cc3634
Build Time: 	Mon, 16 May 2022 11:09:11 +0000
Profile: 	release
Rustc: 		rustc 1.52.1 (9bc8c42bb 2021-05-09)
```
/usr/bin/nydusd --version
```
Version: 	2.0.0
Git Commit: 	1c0598e87dab207286c31ab4cab3025092cc3634
Build Time: 	Mon, 16 May 2022 11:09:11 +0000
Profile: 	release
Rustc: 		rustc 1.52.1 (9bc8c42bb 2021-05-09)
```

**Comment by zvier** [comment]
> > Could you please help to share the output of: /usr/bin/nydusd -h /usr/bin/nydusd --version
> 
> /usr/bin/nydusd -h
> 
> ```
> Version: 	2.0.0
> Git Commit: 	1c0598e87dab207286c31ab4cab3025092cc3634
> Build Time: 	Mon, 16 May 2022 11:09:11 +0000
> Profile: 	release
> Rustc: 		rustc 1.52.1 (9bc8c42bb 2021-05-09)
> ```
> 
> /usr/bin/nydusd --version
> 
> ```
> Version: 	2.0.0
> Git Commit: 	1c0598e87dab207286c31ab4cab3025092cc3634
> Build Time: 	Mon, 16 May 2022 11:09:11 +0000
> Profile: 	release
> Rustc: 		rustc 1.52.1 (9bc8c42bb 2021-05-09)
> ```

Sorry，My new nydusd binary is not update to right position.

**Comment by zvier** [comment]
When the `nydusd` and `containerd-nydus-grpc` version matched, the new problem for create container is failed with message 
```
FATA[0022] creating container: rpc error: code = Unknown desc = failed to create containerd container: mount callback failed on /media/disk1/containerd/tmpmounts/containerd-mount3115484442: read /media/disk1/containerd/tmpmounts/containerd-mount3115484442/etc/passwd: input/output error
```
And containerd-nydus-grpc print a lot of error as follows:
```
[2022-09-16 20:54:14.087893 +08:00] ERROR [error/src/error.rs:21] Error:
	Registry(Request(Common(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("cloud-native-sig-registry.cn-hangzhou.cr.aliyuncs.com")), port: None, path: "/v2/openanolis/anolisos/blobs/sha256:e34b5aee08b12b319ab1c89b52d9c6cbc929acc5f20154eac9c21f984ad72eb1", query: None, fragment: None }, source: TimedOut })))
	at storage/src/cache/mod.rs:207
	note: enable `RUST_BACKTRACE=1` env to display a backtrace
```

**Comment by jiangliu** [comment]
Could you please help to change the communication protocol from "http" to "https"? Maybe your registry only accept https connections.

**Comment by zvier** [comment]
> Could you please help to change the communication protocol from "http" to "https"? Maybe your registry only accept https connections.

Now, my `/etc/nydusd-config.json` is updated to
```
{
  "device": {
    "backend": {
      "type": "registry",
      "config": {
        "scheme": "https",
        "timeout": 5,
        "connect_timeout": 5,
        "retry_limit": 0
      }
    },
    "cache": {
      "type": "blobcache",
      "config": {
        "work_dir": "/cache"
      }
    }
  },
  "mode": "direct",
  "digest_validate": false,
  "iostats_files": true,
  "enable_xattr": true,
  "fs_prefetch": {
    "enable": true,
    "threads_count": 4
  }
}
```
After restart `containerd` and `containerd-nydus-grpc`, the same problem still exist.

**Comment by imeoer** [comment]
@zvier Some configuration is saved to disk once pulled the image, so please try to clean up the nydus snapshot directory first.

**Comment by zvier** [comment]
> @zvier Some configuration is saved to disk once pulled the image, so please try to clean up the nydus snapshot directory first.

Thanks, the test case passed after the nydus snapshot  clean up.
