### ISSUE TITLE
refresh registry token automatically for mirror mode

### ISSUE THREAD

**Issue by imeoer** [dragonflyoss/image-service#821]
- Since dragonfly is slow to forward 401 responses, nydusd registry backend should automatically apply the new auth token in a background thread to minimize the number of 401 responses due to token expiration.
- Maybe we can obtain the token expiration time as a reference for the next time to refresh the token, if can't, use 10 min as the default.
- Share the backend thread with the mirror health check job.

**Comment by imeoer** [comment]
cc @sctb512

**Comment by sctb512** [comment]
It is a good idea to refresh the auth token and avoid forward 401 response to dragonfly. I will add it to the mirror health checking thread soon.

**Comment by sctb512** [comment]
Currently, I have not added it to the mirror health checking thread.
Reason: `refresh registry token` is only available for registry, `connection.rs` is used for OSS backend as well.

Please take a look.

**Comment by imeoer** [comment]
Fixed in https://github.com/dragonflyoss/image-service/pull/800
