### ISSUE TITLE
proposal: an extensible rafs blob format

### ISSUE THREAD

**Issue by imeoer** [dragonflyoss/image-service#873]
OCI v1 Image:

```
[
  oci.blob.tar.gz
  oci.blob.tar.gz
]
```

The new changes on `BlobMetaHeaderOndisk` struct:

```
pub struct BlobMetaHeaderOndisk {
    ...

    /// File offset to get the compressed blob meta data.
    s_ci_compressed_offset: u64,

    /// File offset to get the bootstrap data.
    s_compressed_bootstrap_offset: u64,
    /// Size of bootstrap data.
    s_compressed_bootstrap_size: u32,

    /// File offset to get the chunk digests data.
    s_compressed_chunk_digests_offset: u64,
    /// Size of chunk digests data.
    s_compressed_chunk_digests_size: u32,

    ...
}
```

Nydus Image:

```
[
  raw.blob | chunk.digests | bootstrap | (blob.meta | blob.meta.header)
  raw.blob | chunk.digests | bootstrap | (blob.meta | blob.meta.header)
  merged_bootstrap.tar.gz
]
```

Nydus Ref Image (Zran):

```
[
  chunk.digests | bootstrap | (blob.meta | blob.meta.header)
  chunk.digests | bootstrap | (blob.meta | blob.meta.header)
  merged_bootstrap.tar.gz
]
```

**Comment by jiangliu** [comment]
For ZRan，how about packing all files into a single blob?

**Comment by jiangliu** [comment]
For discussion record:)
![截屏2022-11-21 15 43 12](https://user-images.githubusercontent.com/1931516/202992715-c3d8618f-a3c6-40d9-b02d-6fa7f4702a6e.png)

**Comment by imeoer** [comment]
We call the new nydus blob structure `rafs blob v2`:

- rafs blob v2 (native): `blob.raw | bootstrap | [chunk.digests] | blob.meta | blob.header`
- rafs blob v2 (zran): `bootstrap | [chunk.digests] | blob.meta | blob.header`

The changes for `RafsV6Blob`:

```
struct RafsV6Blob {
    ...
    // SHA256 digest of the blob meta header.
    ci_header_digest: [u8; 32],

    // SHA256 digest of the referenced blob (only valid in merged bootstrap).
    rafs_blob_digest: [u8; 32],

    // Size of the referenced blob (only valid in merged bootstrap).
    rafs_blob_size: u64,

    // Size of the compressed bootstrap data.
    bootstrap_compressed_size: u32,

    // Size of the compressed chunk digests.
    chunk_digests_compressed_size: u32,
    ...
}
```

The changes for `BlobMetaHeaderOndisk`:

```
pub struct BlobMetaHeaderOndisk {
  ...
  /// Digest of uncompressed blob meta data.
  s_ci_digest: [u8; 32],

  /// Digest of uncompressed bootstrap data.
  s_bootstrap_digest: [u8; 32],

  /// Digest of uncompressed chunk digests data.
  s_chunk_digests_digest: [u8; 32],
  ...
}
```

For image (merged bootstrap):

Request registry to get `blob.header`, `blob.meta`, `chunk.digests` (optional) data;

For snapshot view:

Request registry to get `blob.header`, `blob.meta`, `chunk.digests` (optional), `bootstrap` data;

**Comment by changweige** [comment]
better rename `blob.meta.header` to `blob.meta.footer` ?

**Comment by changweige** [comment]
Should also rename BlobMetaHeaderOndisk  to BlobMetaFooterOndisk ?

**Comment by hsiangkao** [comment]
`BlobMetaHeaderOndisk` is too inflexable, many fields are hard-coded at the specific position.
It's a very bad design style, especially for such random toc purpose.

**Comment by imeoer** [comment]
cc @hsiangkao how about like:

```
pub struct TocEntry {
  entry_type: u32,
  digest: [u8; 32],
  offset: u64,
  size: u64,
}
```

`blob.raw | blob.meta | tar header (blob) | bootstrap | tar header (bootstrap) | chunk.digests | tar header (chunk.digests)`

and append with:

`TocEntry (blob.raw) | TocEntry (blob.meta) | TocEntry (bootstrap) | TocEntry (chunk.digests) | tar header (toc.list)`
