### ISSUE TITLE
compressed blob cache is broken

### ISSUE THREAD

**Issue by changweige** [dragonflyoss/image-service#930]
The blob cache can't be stored as compressed in both v2.1 and the master branch. 
When working on a compressed blob cache, IO errors show up. Will raise a PR to fix it thus negotiating resources overhead and local storage efficiency tradeoff.

**Comment by jiangliu** [comment]
I have tested compressed blob cache with master a while ago, it should work. I will double check.

**Comment by changweige** [comment]
Will be fixed by https://github.com/dragonflyoss/image-service/pull/934

**Comment by changweige** [comment]
> I have tested compressed blob cache with master a while ago, it should work. I will double check.

No IO error happens on master branch, but seems it still dose not work. I add some instrumented and debug code. It does not goes into decompress local cache code path

```
index d4546d14..82b7ddcf 100644
--- a/storage/src/cache/cachedfile.rs
+++ b/storage/src/cache/cachedfile.rs
@@ -1174,10 +1174,13 @@ impl FileCacheEntry {
             };
             let mut reader = FileRangeReader::new(&self.file, offset, size);
             if !chunk.is_compressed() {
+                info!("read uncompressed");
                 reader.read_exact(buffer)?;
             } else if self.blob_compressor() == compress::Algorithm::Lz4Block {
                 let mut buf = alloc_buf(size as usize);
                 reader.read_exact(&mut buf)?;
+
+                info!("read compressed cache");
                 let size = compress::decompress(&buf, buffer, self.blob_compressor())?;
                 if size != buffer.len() {
                     return Err(einval!(
@@ -1189,6 +1192,7 @@ impl FileCacheEntry {
                 decoder.read_exact(buffer)?;
             }
         } else {
+            info!("read compressed cache zstd");
             let offset = chunk.uncompressed_offset();
             let size = chunk.uncompressed_size() as u64;
             FileRangeReader::new(&self.file, offset, size).read_exact(buffer)?;
```

**Comment by jiangliu** [comment]
The code below line 1174 is for compressed cache file, and code below 1189 is for uncompressed cache file. Could you please help to verify again?

**Comment by changweige** [comment]
> The code below line 1174 is for compressed cache file, and code below 1189 is for uncompressed cache file. Could you please help to verify again?

Yes. It should work for master branch

**Comment by jiangliu** [comment]
duplicated with #902 ， so close it.
