### ISSUE TITLE
Clarify if nydusd and nydus-image are supporting GZIP

### ISSUE THREAD

**Issue by changweige** [dragonflyoss/image-service#951]
We have smoke test verifying gzip format nydus image, but I am not sure about the current level of support for gzip. Nydus-image has a flag to format as gzip nydus image, however, it is somewhat blurry since the gzip compressor flag is also used to tell it is stargz blobs.

**Comment by jiangliu** [comment]
Nydus supports two types of data blobs:
1) Nydus/RAFS native data blob: the data blob contains data chunks generated by `nydus-image`. GZip is not supported for RAFS native data blobs.
2) OCI compatible data blob, which referencing an OCIv1 tar/targz/stargz data blob. GZip is supported for OCI compatible data blobs.

To summary:
1) nydus-image never generates GZipped data chunks
2) nydus-image can generate data blobs referencing GZipped OCI data blob
3) nydusd supports GZipped OCIv1 targz/tar/stargz data blobs.

**Comment by changweige** [comment]
Thanks @jiangliu for the elaboration.
