### ISSUE TITLE
docs: quickstart with kind + helm charts

### ISSUE THREAD

**Issue by imeoer** [dragonflyoss/image-service#973]
Refer: https://github.com/dragonflyoss/Dragonfly2/blob/main/.github/workflows/nydus-e2e.yml

**Comment by adamqqqplay** [comment]
Work in progress.

**Comment by adamqqqplay** [comment]
Finished in https://github.com/dragonflyoss/helm-charts/blob/main/INSTALL.md

**Comment by adamqqqplay** [comment]
https://github.com/containerd/nydus-snapshotter/pull/444
https://github.com/dragonflyoss/image-service/pull/1205

**Comment by adamqqqplay** [comment]
PR for nydus website
https://github.com/dragonflyoss/image-service-website/pull/18
